### ISSUE TITLE
AEWeb: listing is not always displaying the correct files

### ISSUE THREAD

**Issue by bchamagne** [archethic-foundation/archethic-node#1016]
### Describe the problem you discovered

When AEWeb is listing the files, it is not displaying the correct files. 

For example:

https://testnet.archethic.net/api/web_hosting/000066C9380423B1B774D37F4FFA779AD9B4FA26170BCBCB0C80B83D7E39278E7D81/

![image](https://user-images.githubusercontent.com/74045243/236770868-63ea1b31-8c92-4701-afc3-895857d42f77.png)

https://testnet.archethic.net/explorer/transaction/000066C9380423B1B774D37F4FFA779AD9B4FA26170BCBCB0C80B83D7E39278E7D81

![image](https://user-images.githubusercontent.com/74045243/236770821-733b4f2c-e393-4295-9025-793c519ea822.png)

**Comment by apoorv-2204** [comment]
> Not an issue, this is because the web_hosting will always fetch the latest transaction of the chain. (in order to be able to update a website)

but you only opened it :joy:
