### ISSUE TITLE
UCO price provider: CoinMarketCap update

### ISSUE THREAD

**Issue by bchamagne** [archethic-foundation/archethic-node#1021]
CoinMarketCap changed (maybe not on 100% of people) their UI. We need to update our scraper.

```
** (ArgumentError) errors were found at the given arguments:

  * 1st argument: not a textual representation of a float

    :erlang.binary_to_float("")
    (archethic 1.0.8-rc1) lib/archethic/oracle_chain/services/uco_price/providers/coin_marketcap.ex:49: anonymous fn/2 in Archethic.OracleChain.Services.UCOPrice.Providers.CoinMarketCap.fetch/1
    (elixir 1.14.1) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (elixir 1.14.1) lib/task/supervised.ex:34: Task.Supervised.reply/4
    (stdlib 4.1.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Function: &:erlang.apply/2
    Args: [#Function<0.60956695/1 in Archethic.OracleChain.Services.UCOPrice.Providers.CoinMarketCap.fetch/1>, ["usd"]]
```

_Originally posted by @bchamagne in https://github.com/archethic-foundation/archethic-node/issues/1017#issuecomment-1539795436_

**Comment by samuelmanzanera** [comment]
Indeed by doing `curl` we get the new version of the website
We should have a fallback using:
- get the new class: `sc-8755d3ba-0 PaOrf base-text`
- the meta description parse: 

<img width="1259" alt="image" src="https://github.com/archethic-foundation/archethic-node/assets/14906964/3a5b6da6-cda1-4b09-bcfc-d2e15eb40bb7">
