### ISSUE TITLE
Search transaction should not prioritize invalid tx locally

### ISSUE THREAD

**Issue by samuelmanzanera** [archethic-foundation/archethic-node#1051]
### Describe the problem you discovered

In the current implementation, from the explorer, when we search a transaction we are performing a local search first.
If the local search return an invalid transaction, we're not trying remotely.
Hence, it occurred a node wasn't synchronized properly, as a transaction was marked invalid for a node but for the entire network not.

### Describe the solution you'd like

The search transaction should try locally only to get the transaction if it's not because it's not found or invalid, we should try to fetch the transaction remotely.

**Comment by Neylix** [comment]
This will be fixed in the refactor of TransactionChain module
