### ISSUE TITLE
stats file does not store well the burned fees amount

### ISSUE THREAD

**Issue by Neylix** [archethic-foundation/archethic-node#1059]
### Describe the problem you discovered

The module StatsInfo stores some data after a self repair occurs.
It stores the last burned fees from the last beacon summary aggregate. It stores it in GenServer state and it create a backup file. But the backup file stores the burned fees on 32 bits that have a maximum of 4_294_967_296 which represent only 42,94 UCO.
So if a node restarts and get the last burned fees from the backup file, it may not have the good amount of fees which leads to an error on the next `mint_reward` transaction.

To reproduce the bug:
- Run 2 nodes ans wait them to be authorized
- Run a benchmark or create a transaction with a big NFT collection
- Wait for next self repair
- Restart a node before the next mint reward tx

The next mint reward tx should fail

### Describe the solution you'd like

The backup file should use the VarInt to store the last burned fees.
We may also consider it for the number of transaction even if we are currently far from 4 billions transactions

Don't forget to create a code_change to update the old data to not fail the deserialization

### Additional Context

Epic: #261

**Comment by samuelmanzanera** [comment]
For now all the amount in the transfers are encoded on 64 bits. We should do th same here

**Comment by Neylix** [comment]
> 

In fact we can do this as well, but VarInt in most case would take less space than 64 bits

**Comment by Neylix** [comment]
> > For now all the amount in the transfers are encoded on 64 bits. We should do th same here
> 
> In fact we can do this as well, but VarInt in most case would take less space than 64 bits. And in some way we cannot know or limit the number of fee for a day. Whereas we have an hard limit of the transferable amount

But as the maximum UCO amount is 1 billion, we cannot have more than 1 billion in the fees so 64 bits will be enough
