### ISSUE TITLE
Get the address list of Smart Contrats used in the Secured Message system from a publickey

### ISSUE THREAD

**Issue by redDwarf03** [archethic-foundation/archethic-node#1068]
### Describe the solution you'd like

The messaging system works with smart contracts that have their own chain.
Each smart contract chain represents a discussion group whose members are in the ownerships of the SC.
I need to be able to list the SCs for a public key so that when the user imports his wallet, he can access the list of his discussion groups.

**Comment by samuelmanzanera** [comment]
Would not be more related to the keychain's management and listing of the smart contract associated to the keychain, as opt-in by the user ?

**Comment by redDwarf03** [comment]
This point will be described in the AEIP 6 
https://github.com/archethic-foundation/aeip/blob/main/AEIP-6.md
