### ISSUE TITLE
Speed up DB Chain index loading

### ISSUE THREAD

**Issue by samuelmanzanera** [archethic-foundation/archethic-node#1076]
### Is your feature request related to a problem?

When we restart a node having a lot of data, the DB chain index take some time to load particularly all the transactions from the several subsets.

Right now, the loading of the transaction indexes is sequential which slow down the application startup time.

### Describe the solution you'd like

We should speed up the transaction index loading into the cache by using parallelism of the summary file loading.

### Epic

#261

**Comment by Neylix** [comment]
Done in https://github.com/archethic-foundation/archethic-node/pull/1460
