### ISSUE TITLE
Add faucet rate limiter

### ISSUE THREAD

**Issue by samuel-uniris** [archethic-foundation/archethic-node#111]
We should add a rate limiter for the faucet to avoid someone to drain the pool of UCO dedicated to the faucet.
So we could imagine something like: X amount of UCO for a given address or given IP during a given time.
This will mean we need to timestamp all the faucet transfers in particular process and clear them after the given timespan elapsed.

Knowledge: 
- [x] Checking out Existing Modules Registry related
- [x] Finding the Module Entry points where to place code and testing

We should:
- [x] Implement a GenServer which manages the registry of addresses and timestamps
- [x] Implement a clean up based on timespan
- [x] Prevent faucet transaction if the address is listed in the registry
- [x]  Add Relevant Test Cases
- [ ] Testing on multiple nodes

**Comment by roychowdhuryrohit-dev** [comment]
Assign this to me.

**Comment by I-Archer-Zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/111?planning-poker) with ZenHub @apoorv-2204 @blackode @imnik11 @roychowdhuryrohit-dev @samuel-uniris

**Comment by imnik11** [comment]
we can add `entry{ip, address, timestamp}` in lookup table and then `schedule daily ` check address in the table and based on timestamp & delete those entries after 24 hrs or 48 hrs  and in `faucet_controller.ex` if time limit is passed then allow or if not found then allow

**Comment by samuel-uniris** [comment]
Using a GenServer would do it IMO.
