### ISSUE TITLE
Support function in smart contract

### ISSUE THREAD

**Issue by samuelmanzanera** [archethic-foundation/archethic-node#1173]
### Is your feature request related to a problem?

Sometimes in smart contract we want to extract some part of the code to be reusable for multiple blocks or to structure more your code.
Since the [AEIP17](https://github.com/archethic-foundation/aeip/blob/main/AEIP-17.md), we introduced a way to use function and to expose some through JSON rpc.

### Describe the solution you'd like

To support this feature, we should adapt the interpreter parser to support function capability.

- [x] Private function

We have to support this new syntax 
```elixir
fun myFun do
# Do something
end
```

Function can have 0 or N arity

They can only be called with the smart contract actions or condition blocks

- [x] Pubilc function (exported)

We have to support this new syntax 
```elixir
export fun myFun do
  # Do something and return publically
end
```

Function can have 0 or N arity

They can be called by both private functions, actions or conditions blocks

Their scope should be limited: the parser should prevent :
- to mutate state
- use I/O functions
- contain loops to a certain amount of iterations or complexity

A default allowed complexity has to be defined to be consumed on each instruction (aka gas) limiting the execution of the external functions.

**Comment by Neylix** [comment]
First implementations in #1181 #1199 #1202 #1212
