### ISSUE TITLE
JSONRPC transaction.content should not be base16 anymore

### ISSUE THREAD

**Issue by bchamagne** [archethic-foundation/archethic-node#1232]
### Is your feature request related to a problem?

When using the REST API, we'd have to base16 the transaction.content. This was a legacy decision. 

### Describe the solution you'd like

Now that we have a new API we can remove that legacy

**Comment by samuelmanzanera** [comment]
We can probably use the switch from Ecto the JSON RPC schema validation to simplify the migration, as it might be complex to use either Hex for legacy REST API and type of the JSON RPC API.

**Comment by Neylix** [comment]
> We can probably use the switch from Ecto the JSON RPC schema validation to simplify the migration, as it might be complex to use either Hex for legacy REST API and type of the JSON RPC API.

Since we planned to use OpenRPC standard https://github.com/archethic-foundation/archethic-node/issues/1220
I think we could temporarily add a flag in Ecto has it will be deleted soon with OpenRPC implementation
