### ISSUE TITLE
Reduce replications call by avoiding notifying node movements chains

### ISSUE THREAD

**Issue by samuel-uniris** [archethic-foundation/archethic-node#124]
In the current scheme, during the transaction validation, we are building a node movements list to specify the rewards of the validation nodes and the involved storage nodes. However, this leads to send them the transaction to update their UTXO table and their balance. 

The thing is, while this scheme is acceptable, we will end up to a lot of P2P messages and replications of the transaction which will alter the performance and the throughput of the network. 
For example, if you are taking a network with 50 nodes, and if each shard is composed of 20 nodes, we will have to make 100 Replication messages just to reward the nodes, without counting the recipient and emitter storage pools.

So the idea is to drop this node_movements so you can reward nodes later from their availability using the BeaconChain aggregation from the list of summaries for all the subsets.

More details here: archethic-foundation/archethic-docs#3

This will involve:
- [x] Change the transaction structure and database field
- [x] Change the validation processing to avoid P2P communication
- [x] Remove the field from the UI and Graphql API
- [x] Remove `node_movements` UTXO mem table entries
- [x] Remove the UTXO type `reward`

**Comment by I-Archer-Zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/124?planning-poker) with ZenHub @apoorv-2204 @blackode @imnik11 @roychowdhuryrohit-dev @samuel-uniris
