### ISSUE TITLE
SC: Verify params type in module call

### ISSUE THREAD

**Issue by Neylix** [archethic-foundation/archethic-node#1252]
### Is your feature request related to a problem?

When parsing a contract there is a check to ensure the type of the params, but since all functions accept variables and function call, this check is not very usefull.

### Describe the solution you'd like

We should add a new check when executing the function as all parameters are resolved and are primary types.
This could raise an understandable error

**Comment by bchamagne** [comment]
Maybe we can use https://github.com/Qqwy/elixir-type_check library
