### ISSUE TITLE
Consensus error due to oracle issue

### ISSUE THREAD

**Issue by bchamagne** [archethic-foundation/archethic-node#1350]
### Describe the problem you discovered

Happened 22 times this week on the testnet, 9 times on the mainnet. 

<img width="1043" alt="Capture d’écran 2023-12-13 à 16 17 56" src="https://github.com/archethic-foundation/archethic-node/assets/74045243/06c87356-3719-481d-90b5-990c8e4ba0e6">
<img width="1319" alt="Capture d’écran 2023-12-13 à 16 18 04" src="https://github.com/archethic-foundation/archethic-node/assets/74045243/35041fad-835b-4748-9337-385145727ba7">
<img width="1314" alt="Capture d’écran 2023-12-13 à 16 18 46" src="https://github.com/archethic-foundation/archethic-node/assets/74045243/c3989721-c3e6-450d-bb6d-e83f787ccc98">

### Describe the solution you'd like

How to prevent this?

**Comment by bchamagne** [comment]
CoinMarketCap requests are blocked on some nodes. Here's an example of response:

```
{:ok,
 {{'HTTP/1.1', 403, 'Forbidden'},
  [
    {'connection', 'keep-alive'},
    {'date', 'Wed, 13 Dec 2023 17:10:50 GMT'},
    {'via', '1.1 e5bf2c9645151e78d8b35d4b366f79f6.cloudfront.net (CloudFront)'},
    {'server', 'CloudFront'},
    {'content-length', '919'},
    {'content-type', 'text/html'},
    {'x-cache', 'Error from cloudfront'},
    {'x-amz-cf-pop', 'MAD51-C2'},
    {'x-amz-cf-id', 'AznjqNafspgQZCVpVUmOrQt0busSysnRCbmelMM5UPm0fiSd2kb6kA=='}
  ],
  '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">\n<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">\n<TITLE>ERROR: The request could not be satisfied</TITLE>\n</HEAD><BODY>\n<H1>403 ERROR</H1>\n<H2>The request could not be satisfied.</H2>\n<HR noshade size="1px">\nRequest blocked.\nWe can\'t connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.\n<BR clear="all">\nIf you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.\n<BR clear="all">\n<HR noshade size="1px">\n<PRE>\nGenerated by cloudfront (CloudFront)\nRequest ID: AznjqNafspgQZCVpVUmOrQt0busSysnRCbmelMM5UPm0fiSd2kb6kA==\n</PRE>\n<ADDRESS>\n</ADDRESS>\n</BODY></HTML>'}}
```

**Comment by bchamagne** [comment]
None of the 6 BEYS nodes obtains a result with this function call: `Archethic.OracleChain.Services.UCOPrice.Providers.CoinMarketCapArchethic.fetch(["usd", "eur"])`

I believe it is because they are nodes that contains both Testnet & Mainnet, resulting in too many requests

**Comment by samuelmanzanera** [comment]
Indeed, it can happen even more if the nodes share the same public IP, hence the 6 nodes making the same request might be blocked by external services.

**Comment by bchamagne** [comment]
This happen only on PHY-1 and PHY-2 anymore. Which are nodes hosted at a developer location. The dev environment + the prod nodes are probably triggering the rate limiter from oracle endpoints.
