### ISSUE TITLE
Election of (cross)validators looks wrong

### ISSUE THREAD

**Issue by bchamagne** [archethic-foundation/archethic-node#1353]
### Describe the problem you discovered

While working on the dashboard, I found out that my 4th node (the yellow one below) is almost never elected.
It is only elected when I did faucet because faucets transactions require more validations nodes. 

<img width="1589" alt="Capture d’écran 2023-12-19 à 18 33 13" src="https://github.com/archethic-foundation/archethic-node/assets/74045243/b76e385e-ddca-4c9a-ad5d-d6ae79fdc33e">

There's not much activity on my network: only network transactions & a contract that run every minute
But that should not matter.

### Describe the solution you'd like

The distribution of validators must be more spread

**Comment by Neylix** [comment]
This issue has been discovered and a fix has been provided in this commit: https://github.com/archethic-foundation/archethic-node/pull/1150/commits/4612e197149a119a02c1e0ae0e60d690a0ec409c

However this PR is not ready to be merged, maybe we could pick this commit in a standalone PR
