### ISSUE TITLE
AEIP-21: Use same unspent outputs across validators

### ISSUE THREAD

**Issue by samuelmanzanera** [archethic-foundation/archethic-node#1407]
Coordinator nodes should use only common utxos across all context to build stamp.
The cross validation nodes would have to notify during the context, the list of unspent outputs retrieved.

If some validation nodes are not able to fetch unspent outputs while others can, the transaction should fail.

**Comment by bchamagne** [comment]
I based this work on #1408 which is not merged yet.
Here's the branch: https://github.com/bchamagne/archethic-node/tree/1407-utxo-intersection
