### ISSUE TITLE
Estimate fees for a non signed tx

### ISSUE THREAD

**Issue by redDwarf03** [archethic-foundation/archethic-node#1418]
### Is your feature request related to a problem?

Currently, i can't estimate fees for a non signed tx.
In the case of Dapps, we need to estimate tx's fees but i don't want to use the wallet to sign the tx before the estimation

### Describe the solution you'd like

Update the estimation fees method to allow an estimation without signature info

**Comment by samuelmanzanera** [comment]
A possibility would be to create transaction with fake signatures, as the size remains constant

**Comment by redDwarf03** [comment]
ok
