### ISSUE TITLE
Balance of MUCO is not aggregated

### ISSUE THREAD

**Issue by bchamagne** [archethic-foundation/archethic-node#1506]
### Describe the problem you discovered

<img width="414" alt="Capture d’écran 2024-04-22 à 09 08 47" src="https://github.com/archethic-foundation/archethic-node/assets/74045243/23157ca3-814a-4490-95f1-cd4177cf926a">

### Describe the solution you'd like

Muco should be aggregated together

**Comment by Neylix** [comment]
This is normal, MUCO have multiple addresses. This could be updated with #1262
