### ISSUE TITLE
Expose API to get the origin key

### ISSUE THREAD

**Issue by samuel-uniris** [archethic-foundation/archethic-node#158]
An API should be exposed to get the origin key encrypted by the device's public key.
This API will be used by the client's application to get the list of origin private keys to use for the signature.

- [x] Implement a function to get encrypted origin private keys based on some authorized public key
- [x] Expose through an API
- [x] Add test files

**Comment by I-Archer-Zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/158?planning-poker) with ZenHub @apoorv-2204 @blackode @imnik11 @roychowdhuryrohit-dev @samuel-uniris
