### ISSUE TITLE
Create a program to compute network patch

### ISSUE THREAD

**Issue by ghost** [archethic-foundation/archethic-node#159]
This feature should make available a program in C - to make efficient the algorithm - to build Eigenvectors and Eigenvalues from a list of N*N matrix of latencies and compute the patch

A port will be created to communicate with.
We can maybe explore as well `Nx` which supports matrix operation

**Comment by apoorv-2204** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Workspace-61efec9c93391c001e69a6dc/issues/archethic-foundation/archethic-node/159?planning-poker) with ZenHub @imnik11 @samuel-uniris

**Comment by apoorv-2204** [comment]
hello Team, 
Is this the algorithm Create a program to compute network patch
https://blog.archethic.net/archethic-patches-part2/   ?

**Comment by samuel-uniris** [comment]
Yes
I have the Rust algorithm, but wondering if we are using Rust or switch back to C

**Comment by apoorv-2204** [comment]
I think Rust is good ? what do you think?

**Comment by samuel-uniris** [comment]
Yes sure it's good, but we are using also some C code for TPM/Yubikey/Hypergeometric distribution.
For hardware stuff C will remain the language of low level programming.
And we would have to maintain both stack.

I would like also to explore the road of Matrix computation on Elixir and maybe look at Nx project, if it can help

**Comment by apoorv-2204** [comment]
> Yes sure it's good, but we are using also some C code for TPM/Yubikey/Hypergeometric distribution. For hardware stuff C will remain the language of low level programming. And we would have to maintain both stack.
> 
> I would like also to explore the road of Matrix computation on Elixir and maybe look at Nx project, if it can help

I feel like if rust has libraries to support (for low level access)  then we should move to it,
C feels less secure .
For  Matrix Multiplication we can use this library 
https://github.com/versilov/matrex  
(Its written in C.)

**Comment by apoorv-2204** [comment]
1. erlang naïve matrix multiplication https://zxq9.com/archives/1387
2. erlang  matrix multiplication with nif https://www.info.ucl.ac.be/~pvr/Losseau_45781400_2022.pdf
3.  I think C will be a better choice for number crunching , https://stackoverflow.com/questions/1308527/when-does-erlangs-parallelism-overcome-its-weaknesses-in-numeric-computing
4. Blaze lib in C : https://youtu.be/w-Y22KrMgFE  https://bitbucket.org/blaze-lib/blaze/src/master/

## Its C or Nx, 
### Why Nx,

-  Not other libraries are maintained as much as Nx.
- most of them have releases 1to 3 years old.

### Why C, 

- erlang/elixir not good for crunching numbers, 
- Fastest solution in erlang is based on NIF.
- Erlang parallelism compared with C++ open mp 
   C++ has better performance.
-  lib Blaze , which is fastest matrix computation lib on gcc compiler
- Other parts of AENode, also uses C 
  TPM/Yubikey/Hypergeometric distribution

**Comment by samuel-uniris** [comment]
For NIF in C this can be dangerous if the code is not well written. It's for this reason currently all the C codes are managed through Erlang ports to avoid crash of the entire VM in case of faults

**Comment by samuel-uniris** [comment]
Usually

A NIF:

- Is faster to communicate with, can use native datatypes AFAIK (probably needs some custom work though)
- Needs to be separately written if the program doesn’t already have one
- If it crashes, it takes down the BEAM
- If it stalls, it can adversely affect the BEAM (traditionally NIFs needed to complete in 1ms, nowadays we have dirty schedulers but AFAIK they are not a silver bullet)

A port (external process):

- Slower to communicate with, as communication needs to go through a pipe or other external method and messages need to be serialized for it
- If the program crashes, BEAM is not affected
- If the program stalls, BEAM is not affected
- No need to implement NIF API and make sure it behaves like a NIF should

In most cases a port is fast enough and implementing a NIF is just extra hassle, extra fragility, and may not be worth the effort.

**Comment by apoorv-2204** [comment]
> 1.[Port drivers](http://www.erlang.org/doc/man/erl_driver.html) (sometimes called linked-in drivers) have characteristics similar to ports, but there is no external program involved. Instead, the code, implemented in C/C++, is running directly in the VM.
> 
>2.[NIFs](http://www.erlang.org/doc/man/erl_nif.html) (native implemented functions) can be used to implement Erlang functions in C and run them inside the BEAM. Unlike port drivers, NIFs are not tied to a particular process.
> 
> 3.It is also possible to make your program look like an Erlang node. Some helper libraries are provided for [C and Java](http://www.erlang.org/doc/tutorial/overview.html#id60360). Your Erlang node can then communicate with the program, just like it would do with any other node in the cluster.
> 
> 4.f course, you can always go the “microservices” style: start a separate program, and expose some HTTP interface so your Erlang system can talk to it.

-sasa1977 Sasa Juric
https://www.theerlangelist.com/article/outside_elixir

Option 3 and  4th  ?
Will benchmark elixir Nx.

**Comment by samuel-uniris** [comment]
No it cannot be external.
 
Ports are already used you can check PortHandler.ex using by TPMImpl, LibsodiumPort

**Comment by apoorv-2204** [comment]
> Let me send you the Rust algo

Thank you =)

**Comment by internet-zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/159?planning-poker) with Zenhub @apoorv-2204 @netboz @Neylix @samuelmanzanera @tenmoves
