### ISSUE TITLE
[Feature]: Curve Type in the Transaction address

### ISSUE THREAD

**Issue by samuel-uniris** [archethic-foundation/archethic-node#161]
### Problem to solve

The current address format is built from a hash algorithm type followed by the digest of the address.
```
| Hash algorithm | Address digest
| -------------- |---------------
| SHA2-256       | 0123....
```

This helps to verify the hash.
However, if we want to evolve in terms of cryptography without keeping a track of which curve was used in the previous transaction addresses, we need a way to identify the curve used in the previous transaction addresses

### Solution

The idea is to prepend the address with a byte indicating the curve used.
This way we can evolve inside the chain:

```
| Curve       | Hash algorithm | Address digest
|-------------| -------------- |---------------
| SECP256K1   | SHA2-256       | 0123....
```

So if we are fetching the previous transaction we will see the address and the curve used, then we can derive the key to sign the transaction by using the private key which its public key that generated the previous transaction's address. Therefore the chain of integrity is respected.

**Comment by akshay-reddy-uniris** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/161?planning-poker) with ZenHub @imnik11 @samuel-uniris
