### ISSUE TITLE
Add Onchain Wallet Origin ID

### ISSUE THREAD

**Issue by samuel-uniris** [archethic-foundation/archethic-node#162]
### Problem to solve

When we generate keys, the keystore engine software/TPM, etc... marked the key as generated from a specific origin as hardware or software.
For example, all the software public keys start by 0, the TPM public keys start by 1, etc...
However, we may need to way identify the keys which were generated from the Decentralized Wallet / OnChain (aka. Keychain) to have better observability of the keys generated.

### Solution

So I propose to set the origin id to 0 for OnChain Wallet, which will be the most used in the network, and shift the rest of origin identifications, then:
- OnChainWallet : 0
- Sofware: 1
- TPM: 2

## Tasks
- [x] Coding Part: Updating the `to_origin` and `from_origin`
- [x] Resolving Involved test cases in the test suit.

**Comment by I-Archer-Zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/162?planning-poker) with ZenHub @apoorv-2204 @imnik11 @nilesh-uniris @roychowdhuryrohit-dev @samuel-uniris @blackode
