### ISSUE TITLE
Implement total transaction fee burning

### ISSUE THREAD

**Issue by samuel-uniris** [archethic-foundation/archethic-node#163]
### Problem to solve

https://github.com/archethic-foundation/archethic-docs/issues/3

### Solution

Implement the complete burn of the transaction fee should ease the transaction validation and replication while ensuring a deflation of the UCO value.

This implies:
- [x] Changing the explorer user interface
- [x] Adding the transaction fee burnt for each transaction in the BeaconChain

**Comment by I-Archer-Zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/163?planning-poker) with ZenHub @apoorv-2204 @blackode @imnik11 @roychowdhuryrohit-dev @samuel-uniris
