### ISSUE TITLE
[Bug]: GraphQL error when authorizedPublicKeys is present

### ISSUE THREAD

**Issue by pvalette** [archethic-foundation/archethic-node#177]
### What happened?

The following request provide an internal error
query
{
  transaction(address:"005c61f515b671d7b2c4acc01ae98a970707b43c18aed3a56c4e5b70ff1dfbbf2c") {
   
    data
    {
      ownerships
      {
        secret
        authorizedPublicKeys
        {
          encryptedSecretKey
          publicKey
        }
      }
    }
  }
}

If you remove the section 
      authorizedPublicKeys
        {
          encryptedSecretKey
          publicKey
        }
      }

it works fine

### What is expected ?

To have the list of authorized Public Keys

**Comment by samuel-uniris** [comment]
The issue seams related to a problem of formatting of input data.
From `lib/archethic_web/graphql_schema/transaction_type.ex:94`

**Comment by roychowdhuryrohit-dev** [comment]
It was what I predicted. 

> Here authorized_keys field is not an array...it is a scalar map.

> But in lib/archethic_web/graphql_schema/transaction_type.ex:93 field “authorized_public_keys” expects list_of(list_of(authorized _key)), resulting in mapping issue.
