### ISSUE TITLE
Get the genesis address of the chain

### ISSUE THREAD

**Issue by pvalette** [archethic-foundation/archethic-node#178]
### Problem to solve

From a SC, It could be interesting to have the capability to retrieve the initial address of the caller for example.

This will allow to make some controls on the SC in the condition section for exemple

### Solution

Add a new function in the interpreter
- [x] Add get_genesis_address in library
- [x] Add  fn support in interpreter(whitelist get_genesis_address fn)
- [x] Add GetFirstAddress msg
- [x] Handle NotFound case with GetFirstAddress msg which returns address
- [x] Add test to simulate in actions

**Comment by I-Archer-Zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/178?planning-poker) with ZenHub @samuel-uniris @imnik11 @apoorv-2204

**Comment by I-Archer-Zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/178?planning-poker) with ZenHub @blackode @roychowdhuryrohit-dev
