### ISSUE TITLE
[Question]: How to Verify address

### ISSUE THREAD

**Issue by redDwarf03** [archethic-foundation/archethic-node#201]
### Problem to solve

I would like to verify address structure (like the control in faucet feature)
could you explain me please the algo to control an address 
Thx

### Solution

Just describe the controls

**Comment by imnik11** [comment]
you can leverage `Crypto.valid_hash?()`

**Comment by redDwarf03** [comment]
@imnik11, i saw Crypto.valid_hash but sorry, i don't understand elixir code yet :/ i need help :)

**Comment by redDwarf03** [comment]
… and I prefer put the algo in libdart library than call an api from node please (performance reason)

**Comment by imnik11** [comment]
It is basically concatenation of {(0,1,2,3,4) , hex.digest} based on Hash algorithm ("sha256", "sha512", "sha3-256", "sha3-512", "blake2b")

Example:

1. I use Hash algo sha256 then it will begin with `00` and content will be hashed with sha-256
2. If Hash algo sha512 it will begin with `01` and the content will be hashed with sha-512

similary `02` for `sha3-256`, `03` for `sha3-512`, `04` for `Blake2b`

**Comment by samuel-uniris** [comment]
Hello.

The address's format follow the specific structure:
- An identification byte to describe which algorithm is used in the digest generation (for example sha256, sha3, ...)
- The digest bytes

Ex: 001B5FCD5111745B73A6E5219C700657ED9161D3FC8AD539C95727578C0EC35DAC

00: indicates a sha256
1B5FCD5111745B73A6E5219C700657ED9161D3FC8AD539C95727578C0EC35DAC: Digest of the hash from the next public key 

I hope it will help you

**Comment by redDwarf03** [comment]
implemented here: https://github.com/archethic-foundation/libdart/blob/806424a28e96d899e02d2ae9a73da38a37389ed8/lib/src/crypto.dart#L609

Thank you !
