### ISSUE TITLE
[Feature]: Redirect faucet success alert to the transaction address

### ISSUE THREAD

**Issue by samuel-uniris** [archethic-foundation/archethic-node#204]
### Problem to solve

When a valid transaction is submitted through the faucet controller, the alert redirects to the recipient address but not to the new transaction address .

### Solution

We can easily redirect to the generated transaction address to have a better UX and responsiveness of feedback and audit of the transactions.

**Comment by roychowdhuryrohit-dev** [comment]
Submitted PR #207 that can close this.
