### ISSUE TITLE
[Feature]: Implement replicas confirmation

### ISSUE THREAD

**Issue by samuel-uniris** [archethic-foundation/archethic-node#206]
### Problem to solve

How to ensure a minimun of confirmation from the storage nodes to ensure the data availability of a given transaction. If we are not providing this kind of mechanism, we can end up into a network split / mistmatch where shards and beacon aren't cross linked. Also we do not want to overload the beacon chain by broadcasting it with hundred of messages for single transaction summary.

### Solution

Each validation node will notify the replications nodes in charge, and wait their confirmations to attest the validity and the availability of the transaction in the shard before to notify the beacon chain and the welcome node.

In 1st approx, a single notification from the validation nodes is sufficient to ensure the availability. This attestation will contain a list of signatures, from the replication nodes, to status about their commitment to store the transaction. However, further attestations and confirmations can be checked later during the time, to provide more security.

For example, a beacon chain receiving 1 attestation from a validation node including X storage confirmations will be valid as 3 attestations with their respective confirmations.

When a transaction is submitted, the welcome node will transfer this transaction to the validation nodes and return to the client a pending status. The client would have to subscribe to notifications about the completion of the transaction. Once the transaction will be validated and the validation nodes by notifying the welcome will notify the clients asynchronously.

**Comment by roychowdhuryrohit-dev** [comment]
Why do we need to have all storage nodes with consistent data if we are sharding? Also if we need storage redundancy can we implement some RAID like features where storage nodes will be storing distributed parities? So that data integrity and availability are both maintained with better storage efficiency.

**Comment by samuel-uniris** [comment]
Yes we are using sharding, however, you need to be sure that the nodes in the given shard should have the same information for a given chain - at least some, to ensure consistency.
The storage redundancy is implemented through replication, so multiple nodes are in charge to storage a given transaction chain. If the node doesn't have the information yet, then it will self-repair to fetch the missed transaction.
However, we need to give confirmation from a significant part of the shard to have validated and stored the transaction.
