### ISSUE TITLE
Take the testnet live on atleast 3 AE nodes

### ISSUE THREAD

**Issue by internet-zero** [archethic-foundation/archethic-node#230]
The stable testnet should provides an alternative environment that mimics the mainnet’s functionality to allow users to test the AE Blockchain. The aim is to stabilise the AE Testnet, where the testnet is on atleast 3 nodes.

- [ ] Take the testnet live on on testnet url.
- [x] Take testnet live on separate network with miners to test stability.

**Comment by I-archer-zero** [comment]
The testnet is on docker, and should be fully deployed on all the existing AE nodes

**Comment by I-Archer-Zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/230?planning-poker) with ZenHub @apoorv-2204 @blackode @imnik11 @roychowdhuryrohit-dev @samuel-uniris
