### ISSUE TITLE
Spawn test docker instance as demand

### ISSUE THREAD

**Issue by samuel-uniris** [archethic-foundation/archethic-node#233]
For testing purpose, it should be great to be able to spawn Docker containers as demand instead of leveraging docker-compose network started at a given point and cannot really evolve.

For instance, we may start the network with: the bootstrapping seed, then add linearly some instance, this way we can have a better view how the network will handle new joiners over the time, instead of all in the same time.

This can be achieve easily using `docker-compose up nodeX`

So we might change the `Mix.Task.Archethic.Testnet` to something: `Mix.Task.Archethic.LocalNetwork` where we can generate docker-compose as demand (this is already done, we just need to adapt it)

**Comment by I-Archer-Zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/233?planning-poker) with ZenHub @apoorv-2204 @blackode @imnik11 @roychowdhuryrohit-dev @samuel-uniris

**Comment by AmodD** [comment]
the task of writing a script to cleanup disk space for volumes and containers should be a different issue

**Comment by AmodD** [comment]
should there be an initial task to **manually** demonstrate the expected behaviour ?
or better to break issue into 2 parts 
a.manual
b.script

**Comment by samuel-uniris** [comment]
Sure the 2nd task could be another issue, just we should give the instructions to do the cleanup manually.
