### ISSUE TITLE
Unit | Integration | end to end | otp tests

### ISSUE THREAD

**Issue by apoorv-2204** [archethic-foundation/archethic-node#235]
### What happened?

Critical!! : To be resolved before any updates being pushed to nodes.  
Test data was not removed from the metric dashboard ui.

### What is expected ?

-Removal of  test data from Metric Dashboard UI
-Addition of doc tests to ensure test driven development

**Comment by apoorv-2204** [comment]
https://github.com/archethic-foundation/archethic-node/pull/236

**Comment by I-Archer-Zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/235?planning-poker) with ZenHub @apoorv-2204 @blackode @imnik11 @roychowdhuryrohit-dev @samuel-uniris
