### ISSUE TITLE
Write BeaconSummary transaction timeouts

### ISSUE THREAD

**Issue by samuel-uniris** [archethic-foundation/archethic-node#239]
### What happened?

After a certain amount of time of runtime, the beacon chain crashes due to timeout of the database.
Xandra is returning this error: `Operation timed out - received only 0 responses.`

Because of the BeaconChain crash, the entire app crashes, causing cascading crashes and putting the app in an invalid state.

### What is expected ?

Writing a transaction to the DB should not crash, whatever the size of the transaction.

Lead of investigation:
- log the size of the transaction
- check the `write_request_timeout_in_ms` conf of ScyllaDB
- check the `commitlog_segment_size_in_mb`conf of ScyllaDB
- Backpressure ?
- Retry policy

**Comment by I-Archer-Zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/239?planning-poker) with ZenHub @apoorv-2204 @imnik11 @nilesh-uniris @roychowdhuryrohit-dev @samuel-uniris

**Comment by I-Archer-Zero** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/239?planning-poker) with ZenHub @blackode

**Comment by samuel-uniris** [comment]
As the issue happens in the beacon chain when trying to write summary transaction, try to stimulate load by serializing a long beacon summary with multiple slots. It should timeouts probably due to the latency of the database return.

**Comment by Neylix** [comment]
@samuel-uniris
Is this issue already relevant as new embedded DB was implemented ?

**Comment by samuel-uniris** [comment]
I think you are right, I don't think it is correct now.
