### ISSUE TITLE
Add HTTP port in the node details

### ISSUE THREAD

**Issue by samuel-uniris** [archethic-foundation/archethic-node#243]
### Problem to solve

Sometimes a node can be used different port for the explorer or endpoint for different reason like multiple nodes in the same host.
Even if clients can use the right port for the explorer or the API, internal services like metrics polling leverages public HTTP API. If the port configured is not the default one, the metrics polling will not work.

### Solution

We  should:
- [x] add an information in the node transaction's content to identify the HTTP port used
- [x] add this information in the mem tables and the relative structs
- [x] use this port in the metrics polling
- [x] Update doc tests with new node structure

**Comment by I-Archer-Zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/243?planning-poker) with ZenHub @apoorv-2204 @blackode @imnik11 @roychowdhuryrohit-dev @samuel-uniris
