### ISSUE TITLE
Resolve dark mode in Echarts.

### ISSUE THREAD

**Issue by apoorv-2204** [archethic-foundation/archethic-node#244]
### Problem to solve

When forced dark mode , adjust colors accordingly 
<img width="235" alt="image" src="https://user-images.githubusercontent.com/90304197/155675457-1cf9c995-6306-4e04-8e7b-feb71ca860f9.png">

### Solution

> Before rendering the echarts call a function which returns a color js object  based on time , either day or night, 
> Upon receiving the js object assign the static places with color_obj.line_color , ... etc

**Comment by I-Archer-Zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/244?planning-poker) with ZenHub @apoorv-2204 @imnik11 @nilesh-uniris @roychowdhuryrohit-dev @samuel-uniris

**Comment by apoorv-2204** [comment]
Hello, 
I was not able to replicate The dark mode error, on devices even with
dark mode theme.
W.r.t Theme Management the color black and white will remain 
the same. 
@samuel-uniris

**Comment by samuel-uniris** [comment]
@apoorv-2204 can you try to reproduce it by forcing the dark theme like: `var chart = echarts.init(dom, 'dark');`

**Comment by apoorv-2204** [comment]
> @apoorv-2204 can you try to reproduce it by forcing the dark theme like: `var chart = echarts.init(dom, 'dark');`

Hi @samuel-uniris  
![image](https://user-images.githubusercontent.com/90304197/167467008-384bf2d4-a113-4c9e-ba7e-d2a61f9eb335.png)

I have some ideas.

**Comment by apoorv-2204** [comment]
Hello, @samuel-uniris and @Neylix and @internet-zero and @blackode 
Hello Team,
Guys, What do you think about this dark theme?

![image.png](https://images.zenhubusercontent.com/6138796b9500e12eb0cd6294/224c8b74-7ee0-446d-adc4-d137e4ccd629)

**Comment by samuel-uniris** [comment]
You only changed the website theme but no echarts right ?

**Comment by samuel-uniris** [comment]
> > @apoorv-2204 can you try to reproduce it by forcing the dark theme like: `var chart = echarts.init(dom, 'dark');`
> 
> Hi  @samuel-uniris
> This image is `var chart = echarts.init(dom, 'dark');`
> ![image](https://user-images.githubusercontent.com/90304197/167467008-384bf2d4-a113-4c9e-ba7e-d2a61f9eb335.png)
> 
> ----
> - We can have argument "dark" for echarts,  which gets dark color-scheme for graphs 
>   which apply specific color to each elements of graphs , we can get info regarding the theme 
>  from url dark or blue.
> - In dark Archethic and blue Uniris theme, It will be nice to have  same color schemes
> as it has nice contrast with both the themes. 
> 

Can you force echarts to render in a single mode(i.e light) if we don't have a dark theme for the explorer ?

**Comment by apoorv-2204** [comment]
> You only changed the website theme but no echarts right ?
-  right

Hi, 
from documentation : 
- echarts should automatically  adjust to dark mode (w.r.t background), (But it didn't )
- So I created method for dark and default view to return corresponding chart parameters .
