### ISSUE TITLE
Invalid proof of election

### ISSUE THREAD

**Issue by samuel-uniris** [archethic-foundation/archethic-node#255]
### What happened?

During self repair, when node joins, some transactions are not sync because of the invalidation of the proof of election within the validation stamp.
This is probably due to problem of ordering of the transaction to sync since the last changes.

```
node2_1  | 2022-03-11 08:25:51.372 
[info] 
KO transaction 0000DC41C088F74B7896CAC20243F5A0891C23A2913CFCDB9099805FB37AE36E35F8 

node2_1  | 2022-03-11 08:25:51.372
transaction_address=0000DC41C088F74B7896CAC20243F5A0891C23A2913CFCDB9099805FB37AE36E35F8
transaction_type=oracle
[info] 
Invalid transaction for replication - :invalid_proof_of_election    
```

But this bug is non-deterministic it may happen sometime. 
So this brings the difficulty to catch it.

### What is expected ?

It should not have regression, as sync is the critical part of the system.
Transactions should be sync in order, to avoid election problems.

**Comment by AmodD** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/255?planning-poker) with ZenHub @blackode

**Comment by AmodD** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/255?planning-poker) with ZenHub @samuel-uniris

**Comment by AmodD** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/255?planning-poker) with ZenHub @imnik11 @nilesh-uniris
