### ISSUE TITLE
Implement a tailored embedded data storage engine

### ISSUE THREAD

**Issue by samuel-uniris** [archethic-foundation/archethic-node#260]
The current implementation of the Archethic node is using a wide column database (ScyllaDB/Cassandra) to store network states (chains, transactions, etc.)

However, we are facing some issues regarding latencies, connection based management, industrialization and complex administration.

We want to:
- to cut down the latencies and leverage en embedded database, to remove any connection based storage and connection latencies/pooling resources.
- to rid of limitations present in the data model, hardware requirements and the architecture of database like Cassandra/ScyllaDB.
- implement wide column storage, where we can filter by columns (like a two-dimensional KV storage)
- implement a log storage to support read/write latency/throughput predictable and support high volume of queries
- be able to customize anything to our needs

The first proposal would be to:
- [x] Implement a file storage for transaction chains based on the genesis address. So each transaction chain files will grow over time, by appending the new transaction to the end of the file (as log—AHEAD writing). The raw transaction received from the transaction will be persisted then inside this file.
- [x] Leverage KV storage, to perform the indexation of those files to make reads faster, using file identification and offsets.
- [x] The KV storage would also point the sub columns information to nested KV query, without loading the entire dataset.
- [x] The implementation should be native (Erlang/Elixir), to be faster to reduce communication overheads
- [x] Implement pagination of transaction chain retrieval
- [x] Implement in memory indexing functions to full-fill the DB behavior
- [x] Provide On disk backup of indexes
- [x] Implement bloom filter
- [x] Provide benchmarks regarding the Cassandra/Scylla implementation
- [ ] Adapt existing code

**Comment by I-Archer-Zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/260?planning-poker) with ZenHub @blackode @imnik11 @roychowdhuryrohit-dev @samuel-uniris

**Comment by samuel-uniris** [comment]
Benchmarks:

## Write transaction to a chain
<img width="1278" alt="image" src="https://user-images.githubusercontent.com/42943690/161282131-9e18482b-ee45-48b1-a196-bbef17625c55.png">

## Get transaction
<img width="1278" alt="image" src="https://user-images.githubusercontent.com/42943690/161284618-50bbb68a-12de-420b-84c3-77bef4fe9842.png">

## Get transaction chains
<img width="962" alt="image" src="https://user-images.githubusercontent.com/42943690/161293240-950786e9-6720-4025-86cc-f30fb07ba462.png">
