### ISSUE TITLE
IPLookup is unable to detect and avoid forbidden IP ranges

### ISSUE THREAD

**Issue by roychowdhuryrohit-dev** [archethic-foundation/archethic-node#270]
### What happened?

In many countries the broadband ISPs use internal routing among its users which is why the network configuration at user's end (ex: wifi routers) only contain the internal private ip address and not the absolute public address which is exposed outside the ISP's network. Since the module `ArchEthic.Networking.IPLookup` first uses NAT for deriving user's public address it often includes forbidden(private) IP ranges like 0.0.0.0.

<img width="354" alt="Screenshot 2022-03-30 at 20 10 35" src="https://user-images.githubusercontent.com/24897721/160867171-ee426a01-83d5-46c4-b6de-a59693bb54e7.png">

### What is expected ?

If the IP returned by `IPLookup.NAT` is invalid i.e belongs to the forbidden IP ranges then it will use IPFY to get the correct public IP.

IP ranges to avoid:

https://github.com/archethic-foundation/archethic-node/blob/819b8af47e63411e5e7fdd9e68cb65921ab58463/lib/archethic/networking.ex#L9

**Comment by internet-zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/270?planning-poker) with ZenHub @blackode @imnik11 @roychowdhuryrohit-dev @samuel-uniris

**Comment by internet-zero** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/270?planning-poker) with ZenHub @Neylix
