### ISSUE TITLE
Leverage sharded origin keys

### ISSUE THREAD

**Issue by samuel-uniris** [archethic-foundation/archethic-node#275]
Right now we are using an hardcoded origin shared key, but we should use this hardcoded key as an authorized public key key for the initial origin private keys. 

So the initial origin shared private keys will be encrypted for the hardcoded software public key. 

This requires:
- [x] create first origin shared secrets transaction during the network initialization
- [x] add the initial private keys encrypted for the hardcoded genesis software public key
- [x] add an origin shared chain by family
- [x] add test files

This will have an impact on libjs and wallet as #158 should be implemented to test it.

**Comment by apoorv-2204** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/275?planning-poker) with ZenHub @imnik11 @samuel-uniris @blackode
