### ISSUE TITLE
"gmp.h" header file not found

### ISSUE THREAD

**Issue by roychowdhuryrohit-dev** [archethic-foundation/archethic-node#29]
### Description

Running `iex -S mix phx.server` fails when "gmp.h" dependency in /usr/bin/gcc src/c/hypergeometric_distribution.c is not found.

### Expected Behaviour

Uniris node accessible via _localhost:$PORT_.

### Actual Behaviour

```
src/c/hypergeometric_distribution.c:3:10: fatal error: 'gmp.h' file not found
#include <gmp.h>
         ^~~~~~~
1 error generated.
make: *** [hypergeometric_distribution] Error 1
** (Mix) Could not compile with "make" (exit status: 2).
You need to have gcc and make installed. Try running the
commands "gcc --version" and / or "make --version". If these programs
are not installed, you will be prompted to install them.
```

### Steps To Reproduce

`iex -S mix phx.server`

### Platform

macOS Big Sur 11.2.3

### Possible Solution

A simple `brew install gmp` is one of the easiest way to solve this issue. Please add _gmp_ under installation requirements.

**Comment by Dgetsylver** [comment]
This has not resolve the issue for me. Even though I have GNU make 4.3, GCC 11.0 and gmp installed.

**Comment by roychowdhuryrohit-dev** [comment]
> This has not resolved the issue for me. Even though I have GNU make 4.3, GCC 11.0 and gmp installed.

Can you paste the error log here?
