### ISSUE TITLE
Explorer - Error formatting UCO balance

### ISSUE THREAD

**Issue by redDwarf03** [archethic-foundation/archethic-node#295]
### What happened?

I have a balance with 4.49066628 UCO. and in explorer, I have 449066628

<img width="1440" alt="Capture d’écran 2022-05-01 à 22 50 04" src="https://user-images.githubusercontent.com/68340133/166164111-ff382caa-fb44-4d7b-a58c-1c3470ea19de.png">

### What is expected ?

change displaying of balance with balance/10^8

**Comment by AmodD** [comment]
moving issue to closure as PR#298 for this issue is merged
