### ISSUE TITLE
Use pagination state in GraphQL API

### ISSUE THREAD

**Issue by samuel-uniris** [archethic-foundation/archethic-node#297]
### Problem to solve

GraphQL API `transactionChains` uses pagination mechanism using number.
However it may create confusion which number to use 0 or 1 for the first page causing different results due to implementation `Enum.at/2`.
Also we would like to avoid memory consumption by loading the entire chain.

Related to #296

### Solution

We can leverage the `pagination_state` returned from the DB and provided by the `GetTransactionChain` message.

The parameter will be then be the last address retrieved as the starting point on the chain to be retrieved.

However, for `networkTransaction` API we can still use the page as a number greater than 0, as the state will be different for several chains.

### Development Tasks

- [x] Breaking existing code in to definitions for re-usability for newer approach
- [x] Creating a New Pagination approach based on `paging_address` instead page number where `paging_address` is page's last transaction address
- [x] Add new function resolver to fetch transaction chain based on `paging_address` instead of loading all transactions and slicing down to pages
- [x] Add `networkTransactions` API `page` attribute  validation 
- [x] Add or Update Relevant Unit Test cases for Transaction Chain

**Comment by AmodD** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/297?planning-poker) with ZenHub @apoorv-2204 @blackode @Neylix
