### ISSUE TITLE
Improve Github Actions duration

### ISSUE THREAD

**Issue by samuel-uniris** [archethic-foundation/archethic-node#302]
Right now for a Github Action job to validate a PR take some times. 
We can enhance it by leverage more caching.
Hence we will get a better responsive code quality check.

We can look at: https://hashrocket.com/blog/posts/build-the-ultimate-elixir-ci-with-github-actions 

There are examples how to leverage cache for dependencies and static analysis tool

**Comment by AmodD** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/302?planning-poker) with ZenHub @apoorv-2204 @blackode @Neylix

**Comment by AmodD** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/302?planning-poker) with ZenHub @samuel-uniris
