### ISSUE TITLE
Add telemetry for embedded database

### ISSUE THREAD

**Issue by samuel-uniris** [archethic-foundation/archethic-node#327]
### Problem to solve

We want to have a better monitoring of the database, to detect bottlenecks or area of improvements

### Solution

We have to leverage `telemetry` for:
- [x] Write transaction
- [x] Read transaction
- [x] Read transaction chain
- [x] Indexing

**Comment by apoorv-2204** [comment]
hello Team, 
I think , we might have to add 
```
:telemetry.execute([:archethic, :db], %{duration: System.monotonic_time() - start}, %{
        query: "write_transaction_chain"
      })
```

```
@spec write_transaction_chain(list(Transaction.t())) :: :ok
  def write_transaction_chain(chain) do
    start =System.monotonic_time()

    sorted_chain = Enum.sort_by(chain, & &1.validation_stamp.timestamp, {:asc, DateTime})

    first_tx = List.first(sorted_chain)
    genesis_address = Transaction.previous_address(first_tx)

    Enum.each(sorted_chain, fn tx ->
      unless ChainIndex.transaction_exists?(tx.address, db_path()) do
        ChainWriter.append_transaction(genesis_address, tx)
      end
    end)
:telemetry.execute([:archethic, :db], %{duration: System.monotonic_time() - start}, %{
        query: "write_transaction_chain"
      })
  end

**Comment by AmodD** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/327?planning-poker) with ZenHub @apoorv-2204 @blackode @Neylix @samuel-uniris @nilesh-uniris
