### ISSUE TITLE
Enforce tx size validation in API

### ISSUE THREAD

**Issue by samuel-uniris** [archethic-foundation/archethic-node#330]
Transaction's encoding serializes it in binary format with some limitations, for example the max of UCO tranfsers allowed encoded in 1 byte, resulting into a max of 256 transfers, etc.

So the API which is receiving a transaction to validate should assert the maximum capacity of the transaction as well. 

This will prevent unecessary failures in case of DDoS or spam. 

Actions

- [X] Understand how transaction are send to the APIs (format and changes)
- [X] Understand Transaction Encoding
- [X] Make Changes to Check for Code Length, Extract maximum size from Environment.
- [X] Write a function to return maximum size of a transaction, respective of the transaction encoding.
- [X] Make changes in Transaction Structures
- [X] Integrate with the APIs
- [X] Add Tests if Any

**Comment by internet-zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/330?planning-poker) with ZenHub @blackode @imnik11 @Neylix @roychowdhuryrohit-dev @samuel-uniris
