### ISSUE TITLE
New API for web hosting

### ISSUE THREAD

**Issue by Neylix** [archethic-foundation/archethic-node#333]
### Problem to solve

Related to https://github.com/archethic-foundation/aeweb-cli/issues/60

### Solution

- [x] Create a new API api/web_hosting/:address/*
- [x] Retrieve address transaction content and convert it to json object
- [x] Get file path after address and retrieve content in json object
- [x] Decode file content
- [x] Send back result
- [x] Test file

**Comment by internet-zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/333?planning-poker) with ZenHub @blackode @imnik11 @roychowdhuryrohit-dev @samuel-uniris @Neylix
