### ISSUE TITLE
Detect unresponsive trigger node

### ISSUE THREAD

**Issue by samuel-uniris** [archethic-foundation/archethic-node#338]
### Problem to solve

We are using some trigger node based on election algorithm to send transaction in case of:
- Oracle
- Node shared secrets
- Contract triggers
...

For instance, the first node of the election will be the one to emit the transaction.

However in case of this node is failing or malicious, if the transaction is not sent, we would have the next one, but as the election may not change, the same issue can occurs.

We then have to find a solution to support fallback of trigger nodes

### Solution

We can implement some kind of process which is waiting some events to occur to determine if a transaction or an action have been submitted.

This solution should be enough generic to support multiple implementation based on the several context we are using.

An idea could be to modelize it trough finite state machine like that:
```mermaid
stateDiagram-v2

[*] --> Waiting
Waiting --> SoftTimeout: after some time
SoftTimeout --> Waiting: resend transaction
Waiting --> Confirmed:  submission notified
Confirmed --> [*]
Waiting --> HardTimeout: no response for all the workers
HardTimeout --> [*]
```
Tasks
- [x] - Add FSM with coding steps below 
- [x] - Add send start/exit  message signals to indicate start end states of FSM in NewTransactions
- [x] - Implement resend until confirm or hardtimeout if went to softtimeout from waiting state and if hardtimeout reset

### Coding Steps

 Implement a FSM with the following: 
- [x] - 1. 4 states i.e Waiting, SoftTimeout, Confirmed, HardTimeout
- [x] - 2. Internally perfrom resend based on timouts

**Comment by internet-zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/338?planning-poker) with ZenHub @apoorv-2204 @blackode @imnik11 @Neylix @prix-uniris @samuel-uniris

**Comment by Neylix** [comment]
Resolved in https://github.com/archethic-foundation/archethic-node/pull/395
