### ISSUE TITLE
Update web hosting API to handle splited transaction

### ISSUE THREAD

**Issue by Neylix** [archethic-foundation/archethic-node#340]
### Problem to solve

Actually the API return only the content of the file in the content of the transaction passed in param. But for website over 3 MB we may have multiple transaction to host the website.
So we need to handle mutliple transactions for different file.

### Solution

Solution described in aeweb issue : https://github.com/archethic-foundation/aeweb-cli/issues/62

**Comment by internet-zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/340?planning-poker) with ZenHub @blackode @imnik11 @Neylix @roychowdhuryrohit-dev @samuel-uniris

**Comment by internet-zero** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/340?planning-poker) with ZenHub @apoorv-2204
