### ISSUE TITLE
Use Archethic logo

### ISSUE THREAD

**Issue by samuel-uniris** [archethic-foundation/archethic-node#347]
We can leverage this one: 
https://github.com/archethic-foundation/archethic-assets/blob/main/assets/logos/references_svg/Archethic%20Public%20Blockchain%20-%20White.svg

**Comment by internet-zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/347?planning-poker) with ZenHub @blackode @imnik11 @Neylix @roychowdhuryrohit-dev @samuel-uniris
