### ISSUE TITLE
Fix self repair notifier

### ISSUE THREAD

**Issue by samuel-uniris** [archethic-foundation/archethic-node#348]
A notifier is implemented when the topology changes triggering the a self repair because the shards change

However the process is crashing causing errors from the DB mentioning the transactions don't exist.

This should be fixed to reactive it (being disabled) and support this shard repairing.

**Comment by internet-zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/348?planning-poker) with ZenHub @apoorv-2204 @blackode @imnik11 @Neylix @samuel-uniris @prix-uniris

**Comment by apoorv-2204** [comment]
I think its may be due to #282 .

**Comment by prix-uniris** [comment]
Tasks: 
- [ ] Simulate the Error in Test
- [ ] Fix the Bug
- [ ] Update Tests
- [ ] Remove Debug Flags (if any)

**Comment by samuel-uniris** [comment]
Closed by #487
