### ISSUE TITLE
When the address is empty in transactionChain query, the error is not catched

### ISSUE THREAD

**Issue by redDwarf03** [archethic-foundation/archethic-node#362]
### What happened?

<img width="1081" alt="Capture d’écran 2022-06-02 à 18 47 10" src="https://user-images.githubusercontent.com/68340133/171815789-5e788b5d-673d-470d-a290-465356d4018e.png">
 

### What is expected ?

Catch the error

**Comment by samuel-uniris** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/362?planning-poker) with ZenHub @apoorv-2204 @blackode @imnik11 @Neylix @prix-uniris
