### ISSUE TITLE
Not compatible with latest version of Node JS

### ISSUE THREAD

**Issue by pvalette** [archethic-foundation/archethic-node#377]
### What happened?

When you have a version NodeJS (17.8 for me), when you launch the node, you have an error  'ERR_OSSL_EVP_UNSUPPORTED'.

This can be fixed by using "_export SET NODE_OPTIONS=--openssl-legacy-provider_" but preferable to have a full compatibility

### What is expected ?

To be able to launch the node with the latest version.

At least, to add "export SET NODE_OPTIONS=--openssl-legacy-provider" in the launch/install script, or to add in the documentation.

**Comment by samuelmanzanera** [comment]
This have been resolved by the .tool-versions file on the root of the project.
