### ISSUE TITLE
Token standard implementation

### ISSUE THREAD

**Issue by samuel-uniris** [archethic-foundation/archethic-node#378]
According to archethic-foundation/aeip#1, we now have to implement it.

The token will be minted as before, but using the rules from the standard.

- [X] Validate the JSON in the transaction's content
- [x] Parse the json and extract minting policies (supply, properties identification for the number of utxos)
- [x] For non-fungible token create multi UTXO with ID

**Comment by pvalette** [comment]
This meaning that the current way for creating  NFT (with \n) will change?

**Comment by samuel-uniris** [comment]
> This meaning that the current way for creating NFT (with \n) will change?

Yes indeed, we have create an Archethic Improvement Proposal to create standardization around it (archethic-foundation/aeip#1)

**Comment by internet-zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/378?planning-poker) with ZenHub @apoorv-2204 @blackode @imnik11 @Neylix @prix-uniris @samuel-uniris
