### ISSUE TITLE
Create miner reward pool during network initialization

### ISSUE THREAD

**Issue by samuel-uniris** [archethic-foundation/archethic-node#379]
### Is your feature request related to a problem?

No related to problem but to support the new miner reward mechanism we have dedicate a transaction chain with for the bootstrap funds of rewards.

### Describe the solution you'd like

During the network initialization we have to create a transaction chain to allocate the amount for the bootstrap of the reward tokens.
So, only the first node which initializes the network will do it.
The chain should use a seed (randomly generated) which will be encoded and encrypted in the node shared secrets (replacement of the `network_seed`).
Hence authorized nodes will be able to build transactions to send rewards to the nodes.

During this first transaction, the token will minted (as token) with the initial supply as 1000000

**Comment by internet-zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/379?planning-poker) with ZenHub @apoorv-2204 @imnik11 @Neylix @prix-uniris @samuel-uniris
