### ISSUE TITLE
Mint miner rewards token on self-repair cycle

### ISSUE THREAD

**Issue by samuel-uniris** [archethic-foundation/archethic-node#380]
### Is your feature request related to a problem?

This issue is to provide a way to use the transaction fees burnt and allocate fill the miner reward pool from them.
This should prevent the drain of the miner reward pool and regulate its amount with the fees already paid.

### Describe the solution you'd like

During the self-repair, we already fetching beacon chain summaries to identify the transactions to synchronize.
All the transaction summaries contain the transaction's fee used during validation.
Then we should:
- aggregate the amount of fee burnt during this cycle
- build transaction to mint new tokens on the miner reward chain
- this transaction should be triggered by a given node (and use the trigger node detection to prevent failure)

### Additional context

This is related to #379

**Comment by internet-zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/380?planning-poker) with ZenHub @apoorv-2204 @imnik11 @Neylix @prix-uniris @samuel-uniris
