### ISSUE TITLE
Transform miner reward token to UCO

### ISSUE THREAD

**Issue by samuel-uniris** [archethic-foundation/archethic-node#381]
### Is your feature request related to a problem?

The problem being once the miner reward token is sent to the miner reward address, the token is still without value (like NFT).
The reason is to prevent hot wallet and potential security issue by hacking a wallet containing a lot of UCOs.

Also we want to control more the circulating supply , hence the reward will not be convert right away to UCO during reward phase.

### Describe the solution you'd like

So in order to resolve it, we apply specific rule in the transaction mining to convert miner token into UCO.

When miner's owner want to spend its reward, it will create a transaction to transfer them, and the miners during transaction validation (like the token minting) will:
- mint UCOs according to the reward amount to transfer
- integrate into them into the `transaction_movements` of the validation stamp.

**Comment by internet-zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/381?planning-poker) with ZenHub @apoorv-2204 @imnik11 @Neylix @prix-uniris @samuel-uniris
