### ISSUE TITLE
Schedule sending of reward tokens to the node reward address

### ISSUE THREAD

**Issue by samuel-uniris** [archethic-foundation/archethic-node#382]
### Is your feature request related to a problem?

The self-repair is aggregating and minting the transaction fees into reward tokens and fill the reward pool.
However, the node are not rewarded yet.
Then we have to send them the reward in a regular basis.

### Describe the solution you'd like

To manage the scheduling of the rewards from the chain of rewards, we can:
1. Use smart contracts
   - Within the chain of the rewards
   - Leverage interval triggers
   - Update the list of recipients with set the list of new authorized nodes each time a new authorize node is added
2. Manage it through Elixir 
   - Schedule process using interval
   - Build transaction and apply more complex computations
   - Use the trigger detection algorithm to prevent failure

### Additional context

Related #380  #379

**Comment by internet-zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/382?planning-poker) with ZenHub @apoorv-2204 @imnik11 @Neylix @prix-uniris @samuel-uniris
