### ISSUE TITLE
Improve self-repair summaries download

### ISSUE THREAD

**Issue by samuel-uniris** [archethic-foundation/archethic-node#385]
### Is your feature request related to a problem?

In development environment this case is really present, but since you are adding some network latency around 150-200ms, the time to get the beacon summaries for all subset for a given date, become really long as minutes.

Hence we should propose a way to optimize the requests to reduce the latency

### Describe the solution you'd like

The self-repair could be optimized in few ways:
### Batch of the beacon summaries

For now, for each subset, we are doing multi requests to the same node, leading to latency (nb subsets(=256) * latency).

We should aggregate trough the election to know which nodes are responsible for which subset and then aggregate through a`GetBeaconSummaries` message

### Stream responses

Because of the aggregation of summaries, network latencies and timeouts can occurred if the number of summaries and the transaction summaries inside are significant, as it's a single P2P call.

So we can stream transaction summaries like we are streaming transaction in the `GetTransactionChain` request, by doing multiple calls

**Comment by internet-zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/385?planning-poker) with ZenHub @apoorv-2204 @imnik11 @Neylix @prix-uniris @samuel-uniris
