### ISSUE TITLE
Add release number in the explorer

### ISSUE THREAD

**Issue by samuel-uniris** [archethic-foundation/archethic-node#386]
### Is your feature request related to a problem?

The problem being we don't know which version the mainnet or the testnet is running when we arrive in the explorer.
This is useful for SDK and clients wanting to interact with the testnet and to avoid inconvenience in case of unsupported changes.

### Describe the solution you'd like

We can add an information either in the navbar (like informational icon) or in the Governance/Code section
We can also get the Archethic's app version from Application environment to display it.

**Comment by internet-zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/386?planning-poker) with ZenHub @apoorv-2204 @imnik11 @Neylix @prix-uniris @samuel-uniris
