### ISSUE TITLE
DB crashes when transaction chain not found

### ISSUE THREAD

**Issue by samuel-uniris** [archethic-foundation/archethic-node#398]
### Describe the problem you discovered

![image](https://user-images.githubusercontent.com/42943690/175342319-7b5e2553-992d-45a5-a106-2e089c19d69d.png)

This is coming from the paging address

**Comment by apoorv-2204** [comment]
Any suggestion to replicate this situation?

**Comment by samuel-uniris** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Workspace-61efec9c93391c001e69a6dc/issues/archethic-foundation/archethic-node/398?planning-poker) with ZenHub @apoorv-2204 @imnik11 @Neylix @prix-uniris

**Comment by Neylix** [comment]
Error occurs when parsing paging address

**Comment by Neylix** [comment]
Resolved in #428
