### ISSUE TITLE
Not possible to launch developer version (6/23/22)

### ISSUE THREAD

**Issue by pvalette** [archethic-foundation/archethic-node#401]
### Describe the problem you discovered

Starting from a fresh version of the node of the 'develop' branch, in order to test AIP #2 implementation

When I launch the node, I have a fatal error and so not possible to launch the node.

I know that 'develop' is an unstable branch but just to keep you inform of this, and unfortunately prevent to use the current version.

** (Mix) Could not start application archethic: Archethic.Application.start(:normal, []) returned an error: shutdown: failed to start child: Archethic.Account.Supervisor
    ** (EXIT) an exception was raised:
        ** (ArgumentError) The module Archethic.Account.MemTables.NFTLedger was given as a child to a supervisor but it does not exist.
            (elixir 1.12.2) lib/supervisor.ex:631: Supervisor.init_child/1
            (elixir 1.12.2) lib/supervisor.ex:735: Supervisor.child_spec/2
            (elixir 1.12.2) lib/enum.ex:1582: Enum."-map/2-lists^map/1-0-"/2
            (archethic 0.16.0) lib/archethic/account/supervisor.ex:23: Archethic.Account.Supervisor.init/1
            (stdlib 3.15.2) supervisor.erl:330: :supervisor.init/1
            (stdlib 3.15.2) gen_server.erl:423: :gen_server.init_it/2
            (stdlib 3.15.2) gen_server.erl:390: :gen_server.init_it/6
            (stdlib 3.15.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3

### Describe the solution you'd like

Possibility to launch the node via the develop branch

**Comment by samuel-uniris** [comment]
This have been fixed yesterday lately since 3a2c9a5

**Comment by pvalette** [comment]
Tested and works fine, thank you
