### ISSUE TITLE
Dashboard not mobile responsive

### ISSUE THREAD

**Issue by ghost** [archethic-foundation/archethic-node#406]
### Describe the problem you discovered

Explorer dashboard is not responsible on mobile or table

### Describe the solution you'd like

We should use vertical stack for the metrics and other boxes

**Comment by samuel-uniris** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/406?planning-poker) with ZenHub @apoorv-2204 @imnik11 @Neylix @prix-uniris
