### ISSUE TITLE
Provide a better validation for typed transaction

### ISSUE THREAD

**Issue by ghost** [archethic-foundation/archethic-node#409]
### Is your feature request related to a problem?

Today we have several types of transactions for user:
- `transfer` 
- `hosting`
- `token`
- ...

Even if the types are just a functional meaning and have some relation to the replication scheme and validation context, we should enforce some transaction data structure requirements.

### Describe the solution you'd like

So you can add some minimal criteria for a given type to be respected.
For instance:
- transfer's transaction should contain at least one UCO or Token transfer
- hosting should match the Archethic web deployment format.

But we should probably define another type of transaction for user, when someone doesn't know in which predefined type the transaction should belong for example: smart contract, authorization and encrypted data, etc…

**Comment by samuel-uniris** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/409?planning-poker) with ZenHub @apoorv-2204 @imnik11 @Neylix @prix-uniris
