### ISSUE TITLE
Add node shared secrets chain explorer

### ISSUE THREAD

**Issue by ghost** [archethic-foundation/archethic-node#411]
Provide a UI to list the node shared secrets transactions with pagination

**Comment by samuel-uniris** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Workspace-61efec9c93391c001e69a6dc/issues/archethic-foundation/archethic-node/411?planning-poker) with ZenHub @apoorv-2204 @imnik11 @Neylix @prix-uniris

**Comment by apoorv-2204** [comment]
Please specify the requirements.

**Comment by samuelmanzanera** [comment]
> Please specify the requirements.

The requirements are the same as #413

**Comment by samuelmanzanera** [comment]
Closed by #581
