### ISSUE TITLE
Add origin chain explorer

### ISSUE THREAD

**Issue by ghost** [archethic-foundation/archethic-node#412]
Provide a UI to list the origin transactions with pagination.
We can also provide criteria to select the transactions for a given origin family.

**Comment by samuel-uniris** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Workspace-61efec9c93391c001e69a6dc/issues/archethic-foundation/archethic-node/412?planning-poker) with ZenHub @apoorv-2204 @imnik11 @Neylix @prix-uniris

**Comment by apoorv-2204** [comment]
any specific requirements?

**Comment by samuelmanzanera** [comment]
Closed by #587
