### ISSUE TITLE
Add node rewards chain explorer

### ISSUE THREAD

**Issue by ghost** [archethic-foundation/archethic-node#413]
Reference to #410

**Comment by samuel-uniris** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Workspace-61efec9c93391c001e69a6dc/issues/archethic-foundation/archethic-node/413?planning-poker) with ZenHub @apoorv-2204 @imnik11 @Neylix @prix-uniris
