### ISSUE TITLE
Verify scheduled transaction only happens once

### ISSUE THREAD

**Issue by samuel-uniris** [archethic-foundation/archethic-node#421]
### Is your feature request related to a problem?

Network transaction which are self-triggered should be sent only once in their respective interval.
Hence we should provide some verification during transaction validation

### Describe the solution you'd like

To do so, we can leverage the last time for a given scheduler for a given transaction type and check if a previous transaction have been already sent

**Comment by samuel-uniris** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Workspace-61efec9c93391c001e69a6dc/issues/archethic-foundation/archethic-node/421?planning-poker) with ZenHub @apoorv-2204 @imnik11 @Neylix @prix-uniris

**Comment by Neylix** [comment]
We can create a common function which takes the transaction type in parameters and depending of the type it will get the last schedule time and check there is no transaction for the expected chain since this time

**Comment by samuel-uniris** [comment]
Closed by #534
