### ISSUE TITLE
Webhosting: Some files return an error 503

### ISSUE THREAD

**Issue by pvalette** [archethic-foundation/archethic-node#426]
### Describe the problem you discovered

On the Testnet, I have published this site
https://testnet.archethic.net/api/web_hosting/0000a253806077627b044c3cd5bf8e69140835fa3d383a6479dd2d72dfb84309c34f

Some files like https://testnet.archethic.net/api/web_hosting/000071d9dbe5bab87ec0f1ef173f1ffd9d4da1a9b9f5d344d3ef5951063521724e3a/assets/index.3c75ff5d.js returns an error 503

However, sometime it is possible to access the file directly and return the value

**Comment by Neylix** [comment]
Hello @pvalette 

This error was due to a DDOS mitigation on the nginx server of the testnet. The configuration was too strict, I allowaed more requests / second, it should be fixed.

Thanks !
