### ISSUE TITLE
Deserialization of Beacon Slot failed

### ISSUE THREAD

**Issue by Neylix** [archethic-foundation/archethic-node#430]
### Describe the problem you discovered

When a node receive a message to add a new beacon slot transaction, the deserialization goes wrong on the en of node sync.

![image](https://user-images.githubusercontent.com/26260538/177515608-752e2c45-6cf9-4e70-ba74-bd0d689ab89d.png)

There may be a problem during serialization or deserialization of the end of node sync.
This may be reproductible by stopping node and restarting it 

### Describe the solution you'd like

We should deserialize the Beacon Slot without error

**Comment by apoorv-2204** [comment]
```[error] [availabilities: "", end_of_node_synchronizations: [], end_of_node_synchronizations_bin: "", net_stats_bin: "", network_stats: [], slot_time: ~U[2022-07-06 15:18:40Z], subset: <<196>>, transaction_attestations: [%Archethic.BeaconChain.ReplicationAttestation{confirmations: [{0, <<118, 91, 158, 80, 17, 48, 36, 226, 9, 84, 16, 126, 96, 36, 94, 61, 80, 77, 28, 35, 151, 11, 59, 44, 43, 102, 190, 141, 12, 148, 29, 83, 238, 120, 198, 99, 60, ...>>}], transaction_summary: %Archethic.TransactionChain.TransactionSummary{address: <<0, 0, 196, 228, 9, 135, 20, 222, 235, 191, 124, 13, 103, 186, 38, 253, 144, 21, 219, 177, 204, 88, 34, 142, 117, 38, 83, 121, 198, 151, 73, 183, 57, 135>>, fee: 0, movements_addresses: [], timestamp: ~U[2022-07-06 15:18:33.959449Z], type: :origin}, version: 1}], transaction_attestations_bin: <<1, 0, 0, 196, 228, 9, 135, 20, 222, 235, 191, 124, 13, 103, 186, 38, 253, 144, 21, 219, 177, 204, 88, 34, 142, 117, 38, 83, 121, 198, 151, 73, 183, 57, 135, 0, 0, 1, 129, 212, 23, ...>>]```  end_of_node_synchronizations_bin: "" is empty , thats why

**Comment by apoorv-2204** [comment]
Unable to replicate this issue, after this PR
Fixed multiple pub sub causing crash due to new replication attestations #432

**Comment by Neylix** [comment]
> Unable to replicate this issue, after this PR Fixed multiple pub sub causing crash due to new replication attestations #432

Can you undo this commit ans try again to be sure it is due to this PR
