### ISSUE TITLE
Not possible to start version 5321bff

### ISSUE THREAD

**Issue by pvalette** [archethic-foundation/archethic-node#437]
### Describe the problem you discovered

Based on a fresh installation of 5321bff, the program stops with the following error:

** (Mix) Could not start application archethic: Archethic.Application.start(:normal, []) returned an error: shutdown: failed to start child: Archethic.P2P.Supervisor
    ** (EXIT) shutdown: failed to start child: Archethic.P2P.Listener
        ** (EXIT) an exception was raised:
            ** (MatchError) no match of right hand side value: {:error, :eaddrinuse}
                (archethic 0.17.0) lib/archethic/p2p/listener.ex:27: Archethic.P2P.Listener.init/1
                (stdlib 3.15.2) gen_server.erl:423: :gen_server.init_it/2
                (stdlib 3.15.2) gen_server.erl:390: :gen_server.init_it/6

**Comment by Neylix** [comment]
Hi !
The error ` {:error, :eaddrinuse}` means the port you are trying to listen is already in use. (By default it's 4000 in dev mode and 40000 in prod mode).
Make sure there isn't an other node running on the network or if the port is used by another program.
For this case I think we can catch the error to display a more relevant message.

**Comment by gvqualite** [comment]
Thanks a lot 
yes it was an issue with port
