### ISSUE TITLE
Faucet - Provide control over the transaction chain and all nodes 

### ISSUE THREAD

**Issue by redDwarf03** [archethic-foundation/archethic-node#447]
### Is your feature request related to a problem?

Actually, if a user uses the faucet for an address, he couldn't receive more than 3 transactions in an hour with a node.
We should extend this control for the addresses of the transaction chain et for all nodes

**Comment by internet-zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/447?planning-poker) with ZenHub @apoorv-2204 @imnik11 @Neylix @prix-uniris

**Comment by Neylix** [comment]
To achieve this control, the faucet rate limiter module should store the genesis address of the chain and not the address used in the faucet page

**Comment by prix-uniris** [comment]
We can leverage  P2P.send_message(node, %GetFirstPublicKey{public_key: public_key}) this, to get the first public key from P2P, and in faucet rate limiter we can add first_public_key as key. This can work assuming that the user will stay in same region interacting with same node for the faucet funds.

**Comment by Neylix** [comment]
Also we should increment the counter after the transaction is validated and not before sending.

**Comment by samuel-uniris** [comment]
Closed by #482
