### ISSUE TITLE
No separation per domain for Cookie

### ISSUE THREAD

**Issue by pvalette** [archethic-foundation/archethic-node#448]
### Describe the problem you discovered

There is no isolation between website about  cookies

The User 1 publishes a first site like
The use browses the following url;
https://testnet.archethic.net/api/web_hosting/00008348c569088c20f9ea8f15d26e14511e5a1a4543ce030ed4c12e4a3f0be8dbaa/getCookie.html?name=site
If the ArchEthic explorer was launched before, he should see GA cookies
Now, he browses the url
https://testnet.archethic.net/api/web_hosting/00008348c569088c20f9ea8f15d26e14511e5a1a4543ce030ed4c12e4a3f0be8dbaa/setCookie.html
A new cookie is set, he can see new value "username=User1" via
https://testnet.archethic.net/api/web_hosting/00008348c569088c20f9ea8f15d26e14511e5a1a4543ce030ed4c12e4a3f0be8dbaa/getCookie.html?name=site

Another User published another site. The user 1 access the page of the other site
https://testnet.archethic.net/api/web_hosting/000087b8a0e4cdc4a7641362b984aab128fd5d9deb626a89ffb0de7c718c946745ea/getCookie.html
The cookie "username=User1" is visible even if the web site is published by another person.
He can overwrite the value with https://testnet.archethic.net/api/web_hosting/000087b8a0e4cdc4a7641362b984aab128fd5d9deb626a89ffb0de7c718c946745ea/setCookie.html

So now the value of the username cookie is User2 on all sites.

The current mechanism will not allow to publish professional websites as no isolation

### Describe the solution you'd like

The solution is not to publish website like this
**https://testnet.archethic.net/api/web_hosting/<transactionId>/<page>** as it is the same domain

But to have more this approach used by cloud Provider (Vercel, etc...), ETH provider (Infura...) such as

**https://<transactionId>.hosting.testnet.archethic.net/<page>** or to have a dedicated domain 
**https://<transactionId>.testnet.hosting-archethic.net/<page>** to isolate hosting and  BL explorer + APIs.

This will also facilitate publishing when you have files (img, js css...) imported with "/filename" 

As you use NGNIX, a rule can be written for redirection on the format **https://testnet.archethic.net/api/web_hosting/<transactionId>/<page>**

**Comment by internet-zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/448?planning-poker) with Zenhub @samuelmanzanera @apoorv-2204 @Neylix

**Comment by samuelmanzanera** [comment]
@pvalette I'm not able to reproduce the issue.

I create two websites:

```html
<!DOCTYPE html>
<html>
   <head>
      <title>My Website</title>
    </head>
     <body>
	<h1>My super website</h1>
         <script>
            var cookieName = 'HelloWorld';
            var cookieValue = 'HelloWorld';
            var myDate = new Date();
             myDate.setMonth(myDate.getMonth() + 12);
             document.cookie = cookieName +"=" + cookieValue + ";expires=" + myDate;
         </script> 
     </body>
</html>
```

```html
<!DOCTYPE html>
<html>
   <head>
      <title>My Website 2</title>
    </head>
     <body>
	<h1>My super website 2</h1>
         <script>
            var cookieName = 'HelloWorld2';
            var cookieValue = 'HelloWorld2';
            var myDate = new Date();
             myDate.setMonth(myDate.getMonth() + 12);
             document.cookie = cookieName +"=" + cookieValue + ";expires=" + myDate;
         </script> 
     </body>
</html>
```

But the cookie are well separated:

<img width="1876" alt="image" src="https://user-images.githubusercontent.com/14906964/191499827-5487e03f-bdcf-411f-b3f8-be6c80bc73fd.png">
<img width="1876" alt="image" src="https://user-images.githubusercontent.com/14906964/191499910-2efcdad0-a763-4b07-84c0-67bc30de82b3.png">

**Comment by samuelmanzanera** [comment]
The session key _archethic_key is defined per websites URL, so the cookie should not be impacted

**Comment by pvalette** [comment]
Hello,

By default the cookie is set at path level.
By adding ‘ path=/;’, in the cookie string, you should reproduce the issue

**Comment by samuelmanzanera** [comment]
I still was not able to reproduce the error:

Site 1:
```html
<!DOCTYPE html>
    <html>
    <head>
        <title>My Website</title>
        <link rel="stylesheet" type="text/css" href="./app.css">
    </head>
    <body>
       <h1>My super website</h1>
       <script>
          var cookieName = 'HelloWorld';
          var cookieValue = 'HelloWorld';
          var myDate = new Date();
          myDate.setMonth(myDate.getMonth() + 12);
          document.cookie = cookieName +"=" + cookieValue + ";expires=" + myDate + ";path=/;";
       </script> 
    </body>
</html>
```

Site 2:
```html
<!DOCTYPE html>
    <html>
    <head>
        <title>My Website 2 </title>
        <link rel="stylesheet" type="text/css" href="./app.css">
    </head>
    <body>
       <h1>My super website 2</h1>
       <script>
          var cookieName = 'HelloWorld';
          var cookieValue = 'HelloWorld2';
          var myDate = new Date();
          myDate.setMonth(myDate.getMonth() + 12);
          document.cookie = cookieName +"=" + cookieValue + ";expires=" + myDate + ";path=/;";
       </script> 
    </body>
</html>
```

<img width="1944" alt="image" src="https://user-images.githubusercontent.com/14906964/192456242-f31ca986-e969-4cb0-b8a2-b66bc60ec8c0.png">

<img width="1944" alt="image" src="https://user-images.githubusercontent.com/14906964/192456385-05a8cd29-1aff-4e1d-9780-b2fb6cd1b814.png">

**Comment by samuelmanzanera** [comment]
But in general it's not best practices : https://stackoverflow.com/a/18155490

**Comment by pvalette** [comment]
After the displaying the Website 2, if you back to Website 1, have you "Helloworld"? or "Hellowworld2"?

Yes not a Best Practice, but it is more for securing the platform/future web sites. and avoid issues.

**Comment by samuelmanzanera** [comment]
I got "Helloworld"

**Comment by samuelmanzanera** [comment]
I think the server could not detect the cookie origin if not mentioned in the client because once the request is sent the browser send the cookie defined locally inside the request.
So on the backend site we have not more identification way to restrict it.
So, clients should define if they want to use same cookie name.
However, by using domain names, for instance example.com, example2.com, the cookies will be different.

**Comment by samuelmanzanera** [comment]
Epic: #1062
