### ISSUE TITLE
Certificate for Custom domains

### ISSUE THREAD

**Issue by pvalette** [archethic-foundation/archethic-node#449]
### Is your feature request related to a problem?

Exposing WebSite with HTTPS via a custom domain is a mandatory feature.

It is possible to redirect the Website via DNS (at least with the previous method) but the negotiated certificate is not  the certificate of archethic and not the certificate expected by the browser for the custom domain.

So you have an alert in the browser.

### Describe the solution you'd like

So it will be nice to push also a certificate on the BL for the custom domain (transaction) that we will indicate in the metadata of the website (see other Issues) or another method totally flexible.

The fact to have the format <transactionId>.testnet.archetic.net will also facilitate redirection especially for Dummies in DNS configuration.

**Comment by internet-zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/449?planning-poker) with Zenhub @samuelmanzanera @Neylix @apoorv-2204

**Comment by samuelmanzanera** [comment]
Epic: #1062
