### ISSUE TITLE
[Feature]: Metric Dashboard

### ISSUE THREAD

**Issue by samuel-uniris** [archethic-foundation/archethic-node#45]
It should be good to have a view where we can see the metrics for the local node or globally.

We can use the endpoints `/metrics` to get the exported metrics, but also for the local one use `telemetry.attach`.

Another idea, can be to use circular buffer to have some history from those metrics

Later we could leverage beacon chain to get some metrics

**Comment by ambareesha7** [comment]
for Metrics Dashboard I think there is a library called [PromEx](https://hexdocs.pm/prom_ex/all.html) it supports both Grafana and Prometheus it fits really well with Phoenix application, 
it's just my research

**Comment by samuel-uniris** [comment]
Hi @ambareesha7 .
Thanks but yes I'm aware of PromEx, but in that case we don't to want to rely on centralized server for the public data.
So the idea was to leverage telemetry metrics to display them as a feed, while later aggregate them via several nodes.

**Comment by ambareesha7** [comment]
Ok I got it,

**Comment by ambareesha7** [comment]
I'm working on this task

**Comment by ambareesha7** [comment]
#105
