### ISSUE TITLE
Provide a way to get the last value of an oracle

### ISSUE THREAD

**Issue by redDwarf03** [archethic-foundation/archethic-node#451]
### Describe the problem you discovered

If i would like to find the last value of an oracle, i can't because the networkTransactions api get the first addresses and we have to paging to find the last value. Not easy because we don't know what is the last page too.

### Describe the solution you'd like

Could you provide an API to get the last address of an oracle please

**Comment by samuel-uniris** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/451?planning-poker) with ZenHub @apoorv-2204 @imnik11 @Neylix @prix-uniris

**Comment by redDwarf03** [comment]
if possible while you do this issue, is it possible to add a param in the query to get an oracle for a timestamp (or a period) 
related to https://github.com/archethic-foundation/archethic-wallet/issues/141
Thx

**Comment by samuel-uniris** [comment]
Closed by #532
