### ISSUE TITLE
In Chain Explorer - desc sort & date of the transaction

### ISSUE THREAD

**Issue by pvalette** [archethic-foundation/archethic-node#452]
### Is your feature request related to a problem?

In the Chain Explorer, it is preferable to have a descendant sort per transaction date
As end user need often to see latest transactions

And it will be nice to have the date of the transaction

### Describe the solution you'd like

- Sort by desc date order
- add transaction date

### Additional context

![image](https://user-images.githubusercontent.com/35062602/179393812-00da62ae-2e88-493e-b025-e0ed2f93cef6.png)

**Comment by samuelmanzanera** [comment]
Related to #373
