### ISSUE TITLE
Return fully validated transaction on Transaction Subscriber

### ISSUE THREAD

**Issue by Neylix** [archethic-foundation/archethic-node#456]
### Is your feature request related to a problem?

Actually the transaction subscriber notify each replication attestation as the number of confirmations.
The problem is that when a user wants to send mutiple transaction from the same chain, it has to wait the full validation of a transaction before sending the next.
Actually the user don't know of many confirmations the transaction will have and cannot send the next transaction when it gets the first confirmation because all storage not didn't finished the replication.

### Describe the solution you'd like

We could provide a way to notify the user if the transaction is fully validated or not. There is mutiple options : 
- In the response we can send the number of confirmation and the maximum number of confirmation expected
- We can add a flag in the last confirmation to say that the transaction is fully validated
- We can add an option to the sibscriber to notify either each confirmation or only when all confirmation are received

**Comment by internet-zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Workspace-61efec9c93391c001e69a6dc/issues/archethic-foundation/archethic-node/456?planning-poker) with ZenHub @Neylix @imnik11 @prix-uniris @apoorv-2204

**Comment by samuel-uniris** [comment]
Closed by #489
