### ISSUE TITLE
Beacon chain loading takes to much time on explorer

### ISSUE THREAD

**Issue by Neylix** [archethic-foundation/archethic-node#458]
### Describe the problem you discovered

Beacon Chain explorer takes to much time to load transaction.
We should investigate why and find a solution to speed it up

**Comment by Neylix** [comment]
Beacon live should also get beacon summary from locally available node and not only authorized node

**Comment by internet-zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/458?planning-poker) with ZenHub @apoorv-2204 @Neylix @prix-uniris

**Comment by imnik11** [comment]
Tasks

- [ ] Simulate latency in beacon explorer.
- [ ] modify list tx by date fn to request BeaconSummary data only from locally available nodes.
- [ ] test it with latency using comcast or with 3 nodes with latency.

**Comment by samuelmanzanera** [comment]
Closed by #559
