### ISSUE TITLE
Node ip address should not be visible

### ISSUE THREAD

**Issue by Neylix** [archethic-foundation/archethic-node#466]

**Comment by kgricour** [comment]
Hello @Neylix , where do you see the ip of the nodes in the explorer, please? I will see to remove them.

**Comment by Neylix** [comment]
> Hello @Neylix , where do you see the ip of the nodes in the explorer, please? I will see to remove them.

Hello, actually this issue is under reflexion, I don't think we will do it.
We have some need to get the ip of nodes
