### ISSUE TITLE
Faucet - add a trim in the address field

### ISSUE THREAD

**Issue by redDwarf03** [archethic-foundation/archethic-node#468]
### Is your feature request related to a problem?

if the address contains blank at the end of the address, a control says that the address is malformated

### Describe the solution you'd like

Could you add a trim function before the control please

**Comment by imnik11** [comment]
we can just add this before checking 
 https://github.com/archethic-foundation/archethic-node/blob/559e3d699ac428df4f5f5c7cbd18401e2e60b3e9/lib/archethic_web/controllers/faucet_controller.ex#L45

`    address = String.trim(address)
`

**Comment by samuel-uniris** [comment]
Closed by #476
