### ISSUE TITLE
Support inheritance exception based on proof of ownership

### ISSUE THREAD

**Issue by ghost** [archethic-foundation/archethic-node#47]
Smart contract need a way to be able to escape inherit constraints by proving you are the owner of the contract or being authorized in a specific list of owners.

Because the smart contract's keys must be shared with the nodes to allow self-triggers of transactions, we cannot rely afterward on the chain's private keys to prove the ownership.

However, a new scheme must be created to support bypass and ownership identification.

To do so, we have to rely on knowledge capability of the owner to determine the eligibility. 
A genesis identification scheme can be used to split the knowledge of the chain's owning and the transaction delegation to have a separation of duties within the same chain.

In this scheme, a different key derivation is used for the genesis and the child private keys.

## Key derivation

The genesis private key is used to delegate a seed for the node to derive the next transactions, while keeping the original seed for the owner. 
The address of the transaction will use the delegate keypair while the 1st previous public key (genesis public key of the chain) will use the origin keypair.

```mermaid
flowchart TB
    GenSeed[Genesis seed] --> GenPv[Genesis Private Key]
    GenSeed[Genesis seed] --> GenPub[Genesis Public Key]
    GenPub --> FirstPreviousPub(1st Previous public key)
    GenPv --> GenSign(Sign)
    GenSign --> FirstPreviousSignature(1st previous signature)

    GenPv --> DerExtSeed(Derive)
    StorageNoncePubKey[Storage nonce public key] --> DerExtSeed
    DerExtSeed --> DelegatedSeed[Delegated Seed]
    DelegatedSeed --> DerKey(Derive Keypair)
    Index --> DerKey
    DerKey --> DelPub(Delegated Public key)

    DerKey --> DelPv(Delegated Private key)
    DelPub --> Hash
    Hash --> Address

    DelPub --> NextPreviousPub(nth previous public key)
    DelPv --> DelSign(Sign)
    DelSign --> NextPreviousSignature(nth previous signature)
```

## Verification

Later, when the owner of the contract would like to bypass inherit constraints to update the code, it will generate a new transaction with the new code and including a signature of the new code using the Genesis Private Key. 
The node will then be able to check if this signature matches with the chain's genesis public key.

## Extensibility

However, sometimes we want to extend the way to assert something by having multiple owners or the ownership evolution.
Hence, the smart contract should include a new inherit constraints property: `exception`.
This property will allow defining custom instruction where the inherit conditions will be escaped.

Also, to share the real ownership of the contract, the genesis seed or private key can be encoded in the ownership section of the transaction to be encrypted for multiple authorized public keys. 
This allows to keep the same scheme of verification while having multiple owners.

**Comment by I-Archer-Zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/47?planning-poker) with ZenHub @apoorv-2204 @blackode @imnik11 @roychowdhuryrohit-dev @samuel-uniris

**Comment by AmodD** [comment]
since this is already estimated , can we write down the tasks so as to see possible splitting up of issue ?

**Comment by samuel-uniris** [comment]
I think this should be analyzed more from me, as it was just an idea but no concrete solution yet.
