### ISSUE TITLE
Balance not updated correctly after UCO burn 

### ISSUE THREAD

**Issue by elmaroufy** [archethic-foundation/archethic-node#474]
### Describe the problem you discovered

When we send UCO to the burn address 00000000000000000000000000000000000000000000000000000000000000000000
the balance is not updated with the amount of UCO sent, only transaction fees are considered.

Transactions log : 
+100 UCOs received 
-1 UCO sent to burn address, trx fees : 0.09777947
balance must be 98.90222053 UCO
The value displayed in wallet is 99.90222053 UCO
the balance on the explorer is 99.90222053 UCO 

**Wallet**
<img width="389" alt="image" src="https://user-images.githubusercontent.com/7628780/180668739-6a2ab28a-508c-47be-9b30-addec1948715.png">

**Explorer** 
https://mainnet.archethic.net/explorer/transaction/000002C71CB1DED7195E2BB11F52395353B2668E4631FFBD6CA6E5F20442F999464E

### Describe the solution you'd like
The balance must be updated when UCU are burned

**Comment by redDwarf03** [comment]
Any relations with https://github.com/archethic-foundation/archethic-wallet/issues/222 ?

**Comment by samuel-uniris** [comment]
Closed by #483
