### ISSUE TITLE
Transfer to same address, results in failure due to overwriting.

### ISSUE THREAD

**Issue by apoorv-2204** [archethic-foundation/archethic-node#484]
### Describe the problem you discovered
Found this bug during muco to uco and was already existing in bug bounty.
https://github.com/archethic-foundation/bug-bounty/issues/17

**Comment by apoorv-2204** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Workspace-61efec9c93391c001e69a6dc/issues/archethic-foundation/archethic-node/484?planning-poker) with ZenHub @imnik11 @samuel-uniris

**Comment by Neylix** [comment]
Already fixed in https://github.com/archethic-foundation/archethic-node/pull/403 no ?

**Comment by apoorv-2204** [comment]
Required separate issue for records.

**Comment by samuel-uniris** [comment]
Closed by #403
