### ISSUE TITLE
Pagination issue on `transactions` graphql endpoint

### ISSUE THREAD

**Issue by samuel-uniris** [archethic-foundation/archethic-node#486]
See https://github.com/archethic-foundation/bug-bounty/issues/24

We need to add the `page_type` here instead of `integer`

https://github.com/archethic-foundation/archethic-node/blob/41877b11866edeb9e75ab5829f2c75d5f999365c/lib/archethic_web/graphql_schema.ex#L50

**Comment by apoorv-2204** [comment]
page_type ??

**Comment by samuel-uniris** [comment]
Yes on https://github.com/archethic-foundation/archethic-node/blob/master/lib/archethic_web/graphql_schema/page_type.ex

**Comment by samuel-uniris** [comment]
Closed by #488
