### ISSUE TITLE
TransactionChain.list_transactions_by_type - Expose API 

### ISSUE THREAD

**Issue by redDwarf03** [archethic-foundation/archethic-node#49]
Could you expose please API TransactionChain.list_transactions_by_type
Thx

**Comment by samuel-uniris** [comment]
Hello.
What will be the purpose ? Because this function list the local stored transaction by type but no globally .

**Comment by redDwarf03** [comment]
I would like to display in the mobile wallet the oracle chains like https://mainnet.archethic.net/explorer/chain/oracle

**Comment by samuel-uniris** [comment]
In the case of network transaction : Oracle, Shared Secret, Nodes ... Those transaction are stored in each node , so we could create endpoint to list them based on the type . 

For example:
```
networkTransactions(type: "oracle_summary") {}
```


Any PR is welcome ;)

**Comment by redDwarf03** [comment]
I propose PR #51
