### ISSUE TITLE
GraphQL documentation - tokenID description missing

### ISSUE THREAD

**Issue by redDwarf03** [archethic-foundation/archethic-node#492]
### Describe the problem you discovered

tokenId's description is missing in the graphQL documentation
![Capture d’écran 2022-08-04 à 20 07 54](https://user-images.githubusercontent.com/68340133/182920542-aa8c7562-4797-4bf0-84f6-9d2d16c6b30b.png)

**Comment by samuel-uniris** [comment]
Closed by #496
