### ISSUE TITLE
Explorer - Error when transaction loading

### ISSUE THREAD

**Issue by redDwarf03** [archethic-foundation/archethic-node#500]
### Describe the problem you discovered

When i search the transaction 0000905E46AC30593747F5030BF702B7E6CAA69F94359FEC6225E4A405728B09EFB4 by the explorer search field, it works

When i type in the browser directly the url
https://mainnet.archethic.net/explorer/transaction/0000905E46AC30593747F5030BF702B7E6CAA69F94359FEC6225E4A405728B09EFB4, it doesn't work

**Comment by Neylix** [comment]
This bug was due to a non synchronisation of multiple nodes, and http server redirect sometimes to a node and sometime to other node.
