### ISSUE TITLE
Add unique identification in the token API

### ISSUE THREAD

**Issue by samuel-uniris** [archethic-foundation/archethic-node#503]
### Is your feature request related to a problem?

As we can create multiple tokens in a chain, we want to provide a way to uniquely identify a token not only based on the genesis address but also with some additional data.

The reason is, clients need an easy and fast way to identify unique assets.

### Describe the solution you'd like

By combining name, symbol, genesis address we can compute a hash and get an ID or digest with all those values.
This will identify the token.

**Comment by Neylix** [comment]
Do we need to add more informaitions to be sure that the token is the same ?
I think about properties, type and maybe hooks code. As these informations are part of the token definition, they should be added in the token id.

**Comment by samuel-uniris** [comment]
The thing by adding properties in the identification is in the case of update of NFT collection the properties collection will change, but the token will remain the same.
So to be sure the token remains the same in a collection change, or renewal, we might keep the properties out of the identification.

**Comment by Neylix** [comment]
Ok, so maybe we can have to behavior depending of the token type: 
- if fongible: add properties
- if non fongible: don't take properties

**Comment by prix-uniris** [comment]
The only concern with this approach will be if, we require to change the symbol or name in the future that would change the identity of a token, say in the future more mint for that token. 
If the name and symbol for a token can be constraints in future mints of that token then it will be fine to identify tokens uniquely.

**Comment by samuel-uniris** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/503?planning-poker) with ZenHub @apoorv-2204 @imnik11 @Neylix @prix-uniris

**Comment by samuel-uniris** [comment]
> The only concern with this approach will be if, we require to change the symbol or name in the future that would change the identity of a token, say in the future more mint for that token. If the name and symbol for a token can be constraints in future mints of that token then it will be fine to identify tokens uniquely.

In fact, if the symbol and the name change in the same chain, it should be different.
Otherwise, this will be strange to a have chain with multiple tokens with different names and symbols but still being the same.
If you take Ethereum example, once a token is created you cannot update its name or symbol (unless you are providing a function to it - but not permit by default)

**Comment by prix-uniris** [comment]
Okay so it will be some kind of standard thing implemented on contract details while minting or originating

**Comment by samuel-uniris** [comment]
Closed by #533
