### ISSUE TITLE
Improve replication error explicitness

### ISSUE THREAD

**Issue by samuel-uniris** [archethic-foundation/archethic-node#504]
### Is your feature request related to a problem?

Since #475, we are notifying errors to the welcome.
However in the case of invalid transaction we aren't giving much details to the client.

`TransactionValidator` contains few reason we can leverage
https://github.com/archethic-foundation/archethic-node/blob/7b24e9033c8e4eedae499d494b2154cb9ece0ad1/lib/archethic/replication/transaction_validator.ex#L31-L42

### Describe the solution you'd like

So, instead of returning just invalid error like here:

https://github.com/archethic-foundation/archethic-node/blob/f203bd3ae5c0430e068b5074ab0ca38fe26a5845/lib/archethic/replication.ex#L125-L133

https://github.com/archethic-foundation/archethic-node/blob/f203bd3ae5c0430e068b5074ab0ca38fe26a5845/lib/archethic/p2p/message.ex#L1304-L1305

Hence, we can return the right reason and notify the client about it.

After we could get a detail error (if tx invalid) from the PendingTransactionValidation

**Comment by prix-uniris** [comment]
We can propagate the reason for the replication errors and handle it, that should do it.
As already mentioned reason can be found here:
https://github.com/archethic-foundation/archethic-node/blob/f203bd3ae5c0430e068b5074ab0ca38fe26a5845/lib/archethic/replication.ex#L125

**Comment by samuel-uniris** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/504?planning-poker) with ZenHub @apoorv-2204 @imnik11 @Neylix @prix-uniris

**Comment by samuel-uniris** [comment]
Closed by #513
