### ISSUE TITLE
Enforce resync of last network transactions after bootstrap

### ISSUE THREAD

**Issue by ghost** [archethic-foundation/archethic-node#508]
### Is your feature request related to a problem?

When a node which available and authorized restarts in a short period of time, this node will receive incoming requests for transaction validation.
However, it might miss some network transactions such as `node_shared_secrets` or `oracle`
So the validation will fail since its shared state will be out to date.

### Describe the solution you'd like

To resolve the out of sync issue for network transactions, we can try to re-sync at the end of the bootstrap by:
- fetching and loading the last node shared transaction
- fetching and loading the last oracle transaction

Hence, the node will be able to validate those transactions in the same state as others will do

**Comment by samuel-uniris** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/508?planning-poker) with ZenHub @apoorv-2204 @imnik11 @Neylix @prix-uniris

**Comment by apoorv-2204** [comment]
- we can get paging address from DB, then request node to return tx s after  that.
- we may require to have DB.EmbeddedImpl for returning last 10 txns or last txs by paging address in future (for blind case scenario where paging address not available)
