### ISSUE TITLE
Make sure the P2P view is up-to-date before to sync transactions

### ISSUE THREAD

**Issue by samuel-uniris** [archethic-foundation/archethic-node#509]
### Is your feature request related to a problem?

During the self-repair, we are downloading beacon summary and aggregates them.
Then we are trying to synchronize missed transactions and after sync the P2P view.

The problem is when a node with a better network connection will sync faster than another; the another one will be late in the P2P view update (as the transaction synchronization takes longer than P2P view update)

This might cause validation node election errors, and failure of transaction validation until complete sync.

### Describe the solution you'd like

So in order to tackle this problem, we might change the ordering of processing in `lib/archethic/self_repair/sync.ex` in the `process_summary_aggregate/2` fn.

1. Update the P2P view
2. Synchronize the transactions

**Comment by samuel-uniris** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/509?planning-poker) with ZenHub @apoorv-2204 @imnik11 @Neylix @prix-uniris

**Comment by apoorv-2204** [comment]
updating p2p view first  instead of :beacon ??

**Comment by samuel-uniris** [comment]
Not at all, instead of synchronize transaction then update P2P, we can do the opposite.
