### ISSUE TITLE
Handle sending timeouts in P2P clients

### ISSUE THREAD

**Issue by ghost** [archethic-foundation/archethic-node#510]
### Is your feature request related to a problem?

Currently, when we are sending a P2P message, you are passing some timeouts based on the message and the expected response.
However, we are not taking in consideration the timeout to send a message.

If for instance we expect a message to take 2s to be returned, and if the node latency is high, the we might take 1s to send the message, and we will get the response at the 3ths.  This will cause an error timeout.

### Describe the solution you'd like

To challenge the timeout issues, we can handle a first timeout based on the message sending (i.e ~1s) and then schedule the appropriate timeout for the response + maybe some sending timeout back.

So when we are sending a message, we are firstly expecting the completion and success of the sending message, otherwise we are returning a timeout error upfront.
Then we are awaiting the real timeout.

This should improve our timeout handling

**Comment by samuel-uniris** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/510?planning-poker) with ZenHub @apoorv-2204 @imnik11 @Neylix @prix-uniris

**Comment by apoorv-2204** [comment]
also-? we can have a start timeout message sent back by a node when it receives intended Message,
notify the requesting node that it can start timeout. To address upload and download time of data and latency.

but we will need to have standard timeout to revive Start Timeout message depending upon request.

I dont know how feasible this is. We can also consider upload and download speed , processing power of node to allocate timeout. like: Node performance score  ??

**Comment by samuel-uniris** [comment]
This might be chicken and eggs problem, but we could leverage upload speed by tracking for each send a node is doing.
By default we can start by 1s.

**Comment by samuelmanzanera** [comment]
Closed by #558
