### ISSUE TITLE
Add the possibility to get the inputs in the smart contract

### ISSUE THREAD

**Issue by Neylix** [archethic-foundation/archethic-node#512]
### Is your feature request related to a problem?

In order to enhance the scalabily of the smart contract, we can use some batching process.
This can work like this: create a smart contract triggered by interval, at the trigger time the smart contract will take all the inputs it got since the last trigger time and doing some actions.

### Describe the solution you'd like

So to do this batching process we have to provide the way to get the inputs and all data associated (content, uco transfer ...) in the smart contract.

We can imagine a fonction like `get_inputs` that return a list with all the inputs of the smart contract. These inputs would have the same attribute as a transaction.

**Comment by samuel-uniris** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/512?planning-poker) with ZenHub @apoorv-2204 @imnik11 @Neylix @prix-uniris
