### ISSUE TITLE
Amount management. Int format (10^8) from end to end 

### ISSUE THREAD

**Issue by redDwarf03** [archethic-foundation/archethic-node#517]
### Describe the solution you'd like

In order to manage the same format of the amounts from end to end, it's necessary to change the answers of queries graphQL to obtain the amounts in int format (10^8)
it concerns :
```Balance.uco```
```TokenTransfer.amount```
```UCOTransfer.amount```
```TransactionInputs.amount```

**Comment by samuel-uniris** [comment]
Closed by #518

**Comment by redDwarf03** [comment]
The fee property in transaction_fee API was forgotten
I reopen this issue to fix it
https://github.com/archethic-foundation/archethic-node/blob/4c9a983a4e081885c14583e3e27bc1371d195997/lib/archethic_web/controllers/api/transaction_controller.ex#L108

**Comment by samuel-uniris** [comment]
Closed by #539
