### ISSUE TITLE
Handle conflicts in the resolving of the last transaction addres

### ISSUE THREAD

**Issue by samuel-uniris** [archethic-foundation/archethic-node#520]
### Describe the problem you discovered

To resolve the last transaction address, we can get multiple answers from the nodes and we are not providing some conflict resolutions.
If a node have not the right address in case of out of sync, the resolve is not working and the data become stale.

### Describe the solution you'd like

We should indicate the timestamp of the last transaction address answer so we could manage and take the latest.

**Comment by apoorv-2204** [comment]
In P2P message we add a field call timestamp, which indicates last address validation time, and in P2p .quorum read method of resolve last address we pick with latest timestamp?

**Comment by samuel-uniris** [comment]
> 

This is the idea

**Comment by samuel-uniris** [comment]
Closed by #527
