### ISSUE TITLE
Use authorized node in the election to fetch transaction details remotely

### ISSUE THREAD

**Issue by samuel-uniris** [archethic-foundation/archethic-node#521]
### Describe the problem you discovered

Currently the election of sharding for the replication is different than the election used in the retrieval (see lib/archethic/transaction_chain.ex and lib/archethic.ex)

### Describe the solution you'd like

We should use the same to have the same election and the right nodes

**Comment by apoorv-2204** [comment]
So whenever we have election, we should get nodes for election from P2P. authorised_and_available_nodes.

**Comment by samuel-uniris** [comment]
> So whenever we have election, we should get nodes for election from P2P. authorised_and_available_nodes.??

This would be the best; to make sure the shards remain constant

**Comment by samuel-uniris** [comment]
Closed by #530
