### ISSUE TITLE
Drop transaction in beacon chains for slot and summaries

### ISSUE THREAD

**Issue by ghost** [archethic-foundation/archethic-node#523]
### Is your feature request related to a problem?

From now we are using transaction chains for the beacon chain itself.
However this brings few drawbacks and problems:
- TPM latency issue: too much origin signature to perform (ie 256 signature in the same time during beacon summary)
- Waste of data stored (useless transaction_data serialization)
- Too long to fetch the transaction chain summary
- Not global view of the slots (only one transaction passed)

### Describe the solution you'd like

We can leverage beacon summary directly into the cache:
- Aggregate multiple slots for a given subset and time
- Faster serialization and retrieval in the beacon chain explorer (direct hit of the summary cache)
- No need to have signatures for the beacon , as the summary is stored locally and not with consensus
- Need to add a new message to get the summary from the cache
- Write to disk to persist cache in case of failure
- Write to disk the summary in a new files/folders

**Comment by internet-zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/523?planning-poker) with Zenhub @apoorv-2204 @Neylix @prix-uniris @samuel-uniris

**Comment by samuelmanzanera** [comment]
Closed by #559
