### ISSUE TITLE
TokenAddress naming

### ISSUE THREAD

**Issue by redDwarf03** [archethic-foundation/archethic-node#525]
### Describe the problem you discovered

In TokenTransfer, the token's address field is "token"
In TransactionInput, the token's address field is "tokenAddress"
Why ?

Could you uniformise with "tokenAddress" ?

**Comment by samuel-uniris** [comment]
Would you prefer `tokenAddress` ?

**Comment by redDwarf03** [comment]
yes please

**Comment by internet-zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/525?planning-poker) with Zenhub @apoorv-2204 @Neylix @prix-uniris @samuel-uniris

**Comment by samuelmanzanera** [comment]
Closed by #549
