### ISSUE TITLE
Restrict extended cron expression in smart contract.

### ISSUE THREAD

**Issue by ghost** [archethic-foundation/archethic-node#540]
### Describe the problem you discovered

See https://github.com/archethic-foundation/bug-bounty/issues/40

### Describe the solution you'd like

I propose to add a parameter in the `Utils.time_offset` to mark the usage of extended mode or not.

**Comment by internet-zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/540?planning-poker) with Zenhub @apoorv-2204 @Neylix @prix-uniris @samuel-uniris

**Comment by samuelmanzanera** [comment]
Closed by #553
