### ISSUE TITLE
Prevent schedulers to be launched before end of bootstrap

### ISSUE THREAD

**Issue by ghost** [archethic-foundation/archethic-node#543]
### Describe the solution you'd like

We can leverage persistent term `archethic_up` in the init and during node_update to start the schedulers

**Comment by internet-zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/543?planning-poker) with Zenhub @samuel-uniris @Neylix @apoorv-2204 @prix-uniris

**Comment by samuelmanzanera** [comment]
Closed by #552
