### ISSUE TITLE
Explorer Inputs misplaced

### ISSUE THREAD

**Issue by samuelmanzanera** [archethic-foundation/archethic-node#560]
### Describe the problem you discovered

<img width="2336" alt="image" src="https://user-images.githubusercontent.com/14906964/188876216-8a9567c0-5203-4a37-9728-f436137c753a.png">

The inputs are located in a tab but also a the bottom of the page

### Describe the solution you'd like

We should only have the inputs information on the tab

**Comment by aime-risson** [comment]
Are you referring to the transaction movements tab and first ledger tab ?

**Comment by Neylix** [comment]
> Are you referring to the transaction movements tab and first ledger tab ?

I think it's more related to the text on the bottom of the page "There are no matching inputs" which shouldn't be there

**Comment by aime-risson** [comment]
Ok wasn't sure thanks

**Comment by Neylix** [comment]
Hello,
This bug is fixed in #580, error was due to a missplaced `</div>` there
https://github.com/archethic-foundation/archethic-node/blob/ed1e678e9046d519af87c77ba4c9f1aff8ab18ee/lib/archethic_web/templates/explorer/transaction_details.html.leex#L352

**Comment by samuelmanzanera** [comment]
Closed by #580
