### ISSUE TITLE
Add timestamp in the unspent outputs

### ISSUE THREAD

**Issue by samuelmanzanera** [archethic-foundation/archethic-node#564]
### Describe the problem you discovered

Transaction inputs are associated with a timestamp, however unspent outputs are not during the transaction validation.
While the UTXO are consumed and the change address is used, this is not causing a problem, but if we want to use tokens and not aggregate them, not having timestamp make harder displays.

### Describe the solution you'd like

To tackle this problem, we can:
- add a field in the unspent output
- if the UTXO is consumed and the change address is used, we can use the transaction validation time
- if the UTXO is not used, we keep it with its timestamp

Then we when will load in the memory tables, we will just keep the timestamp of the unspent output instead of the transaction validation's timestamp.

**Comment by samuelmanzanera** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Workspace-61efec9c93391c001e69a6dc/issues/archethic-foundation/archethic-node/564?planning-poker) with Zenhub @prix-uniris @apoorv-2204 @Neylix

**Comment by apoorv-2204** [comment]
> While the UTXO are consumed and the change address is used, this is causing a problem, 
Please determine how?

**Comment by samuelmanzanera** [comment]
Closed by #621
