### ISSUE TITLE
Improve node availability in beacon slots

### ISSUE THREAD

**Issue by Neylix** [archethic-foundation/archethic-node#569]
### Describe the problem you discovered

Actually, to inform the availability of a node in a beacon slot, nodes ping the other node and if the node respond, it means that the node is available and if the node do not respond, it means that it is not available.
The problem with this implementation is that we have an availability bit at a specific time like a snapshot, but it may not be relevant as the node can be available all the time, but do not respond to this ping for some reason.

### Describe the solution you'd like

An idea to have a more precise availability for a node is to monitor the time where the node is available during a slot time.
As so we have a more accurate value to determine if the node is really available or not as if a snapshot was created each second.

At summary time, we will have all slots from all beacon nodes so we can calculate a median on all available times for a specific node. This median will give us the available time and as we know the time between 2 slot, we can determine if the node is available or not.
We can also add a weighting to slots to prioritize the last slots as they are more relevant than the first slots.

**Comment by samuelmanzanera** [comment]
Closed by #574
