### ISSUE TITLE
Validate smart contract calls

### ISSUE THREAD

**Issue by ghost** [archethic-foundation/archethic-node#57]
## Rationale

When a transaction is targeting a smart contract through the `recipients` field in the transaction data, we should provide a way to check if the transaction would be valid before to send.
Hence, clients can call this endpoint to be sure the transaction will pass.

## Why not doing it during transaction validation ?
Because if the transaction calls are invalid, we don't want a user to spam the network making DDOS attack for nothing and do not pay the fee as the transaction would be not valid.
So by letting the transaction be validated and refused on the smart contract side, we are using the fee as a security mechanism for malicious attacks towards smart contracts.

## How to do it

We should provide an API to check the validity of the smart contract call. 
This API should:
- [ ]  Download transaction's code of the smart contract targeted
- [ ]  Interpret the transaction conditions with the pending transaction as input
- [ ] Return errors or success

**Comment by I-Archer-Zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/57?planning-poker) with ZenHub @apoorv-2204 @blackode @imnik11 @roychowdhuryrohit-dev @samuel-uniris

**Comment by internet-zero** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/57?planning-poker) with Zenhub @Neylix
