### ISSUE TITLE
Certificate in origin_key api is not checked

### ISSUE THREAD

**Issue by Neylix** [archethic-foundation/archethic-node#584]
### Describe the problem you discovered

Actually, when origin public key is not tpm family, we do not control the certificate.
But someone can put some data in the certificate attribute in the api and so create a transaction with some data inside.
As origin transaction are free and generated by nodes, people can create not tpm public key and store data in the transaction for free

### Describe the solution you'd like

In the API or in pending validation, if the origin public key is not tpm family, certificate should be empty

**Comment by samuelmanzanera** [comment]
You should maybe leverage: `Crypto.verify_key_certificate?` to attest the public key with the certificate
