### ISSUE TITLE
Invalid transaction movement during self repair

### ISSUE THREAD

**Issue by Neylix** [archethic-foundation/archethic-node#594]
### Describe the problem you discovered

How to reproduce the error
- Run a node and launch a local benchmark `mix dev.lbench`
- Wait for the benchmark to finish and for the next beacon summary
- Launch a second node and a `invalid_transaction_movements` should be raised

![image](https://user-images.githubusercontent.com/26260538/192986815-92a16943-4289-4468-aff4-30ff45ba73ec.png)

### Describe the solution you'd like

Self repair should load all transaction correclty

**Comment by samuelmanzanera** [comment]
Closed by #597
