### ISSUE TITLE
Specify the hash algorithm in the SC library functions

### ISSUE THREAD

**Issue by samuelmanzanera** [archethic-foundation/archethic-node#610]
For now, we have a single hash function, which is using the default algorithm.
However, to be interoperable with other chains, we should allow specifying which algorithm to use.
We can either:
- create multiple functions for several hash algorithms: `sha2_256(), `sha2_512`, ...
- pass a parameter to the function to specify the algorithm to use

**Comment by internet-zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/610?planning-poker) with Zenhub @apoorv-2204 @netboz @Neylix @samuelmanzanera @tenmoves

**Comment by apoorv-2204** [comment]
do we want to add support in aenode also  for hashes=>
   :sha224,
      :sha256,
      :sha384,
      :sha512,
      :sha3_224,
      :sha3_256,
      :sha3_384,
      :sha3_512,
      :blake2b,
      :blake2s 
???

**Comment by samuelmanzanera** [comment]
You can use the one supported in the conf `:sha256,
    :sha512,
    :sha3_256,
    :sha3_512,
    :blake2b`
This will be sufficient for now
