### ISSUE TITLE
Add comparison date function in the SC library

### ISSUE THREAD

**Issue by samuelmanzanera** [archethic-foundation/archethic-node#615]
We should add function to check `before` and `after` a date, to enhance the SC library functions.

**Comment by internet-zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/615?planning-poker) with Zenhub @apoorv-2204 @netboz @Neylix @samuelmanzanera @tenmoves

**Comment by samuelmanzanera** [comment]
Reopen this issue, as it will remove redundancy to check timestamp of the transaction for instance.
Because this is not valid:
```
condition transaction: [
  timestamp: < unix_timestamp
]
```

we could indeed as something like: 
```
condition transaction: [
  timestamp: before(unix_timestamp)
]
```
