### ISSUE TITLE
Check the validity of addresses in the SC statements

### ISSUE THREAD

**Issue by samuelmanzanera** [archethic-foundation/archethic-node#616]
In the SC SDK, we have some transaction statements to build a new transaction.
We are performing check whether the hex is valid or not, but not discard the statement results if the hex is not valid.
We should check if the hex is valid and prevent the assignment of the statement if not.
Furthermore, we should also check whether the addresses are valid or not.

**Comment by internet-zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/616?planning-poker) with Zenhub @apoorv-2204 @netboz @Neylix @samuelmanzanera @tenmoves

**Comment by bchamagne** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/616?planning-poker) with Zenhub @bchamagne
