### ISSUE TITLE
Purge Account UTXO table once an input is spent

### ISSUE THREAD

**Issue by samuelmanzanera** [archethic-foundation/archethic-node#624]
### Is your feature request related to a problem?

All the inputs are currently store in memory.
In order to scale, you should evict the spent transaction outputs from the ETS tables and store them on disk for a later query.

### Describe the solution you'd like

After each transaction replication, you are notifying the previous shards for a new transaction in the chain.
Hence, the UTXO are flagged as spent.
We could then at this time delegates to a permanent storage on disk to reduce the footprint of the ETS tables.

**Comment by internet-zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/624?planning-poker) with Zenhub @samuelmanzanera @Neylix @apoorv-2204
