### ISSUE TITLE
Determines whether transaction input is spent from the last transaction in the chain

### ISSUE THREAD

**Issue by samuelmanzanera** [archethic-foundation/archethic-node#627]
### Is your feature request related to a problem?

Our UTXO model ensure the inputs are spent for each transaction (re-created).
After #621, if a token is not used, it's marked as spent in the previous transaction and unspent in the next one.
This is a strange behavior for the UTXO model.
We should be able to determine whether a transaction input is spent based on the last transaction on the chain.

### Describe the solution you'd like

After #624, the spent UTXO would not accessible in the MemTables.
Hence, to determine if the input is really spent (logically speaking within the entire chain), we should provide a way to determine this.

In the P2P request to fetch transaction inputs of a previous transaction, from the spent assets (stored on disk – after #624), we can request the last transaction of the chain to determine if the input is an UTXO.
Then we could flag the input as not unspent.

The explorer and the API will then be impacted in the way they retrieve information.

**Comment by internet-zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/627?planning-poker) with Zenhub @samuelmanzanera @apoorv-2204 @Neylix
