### ISSUE TITLE
Add new API to get beacon aggregate

### ISSUE THREAD

**Issue by Neylix** [archethic-foundation/archethic-node#639]
### Is your feature request related to a problem?

Since the PR #559 beacon and beacon summaries are not anymore transactions. Before we could get these transaction using graphql API `networkTransaction`, but now we don't have any way to get the summary data.

### Describe the solution you'd like

We should create a new schema in graphql like `beaconSummary` with a date in parameter which returns the beacon aggregate for this date.
If the date is the last summary date, API should use beacon summary and not beacon aggregate as it is done in explorer.
The date in parameter may be in this format "AAAA-MM-JJ".

### Additional context

I think we should't create an API that returns mutiple summaries as they can contains a lot of data.
Maybe we can create a new type for the transaction summaries which is paginated or have a size limit like
```
query {
  beaconSummary(date: "2022-10-18") {
    transactionSummaries(limit: 100) {
      address
    }
  }
}
```

**Comment by samuelmanzanera** [comment]
Good idea. 
However I suggest to use Unix timestamp instead which is more universal in term of encoding.

**Comment by Neylix** [comment]
> Good idea. However I suggest to use Unix timestamp instead which is more universal in term of encoding.

I thought about this but if it's not exactly a summary time, we have to calculate the exact summary time,. but which one, the previous or the next ?

Let's we have the timestamp of a transaction, if we request a summary with this timestamp, do we want to return the next summary (which contains the transaction) or the past summary ?

**Comment by samuelmanzanera** [comment]
> we request a summary with this timestamp, do we want to return the next summary (which contains the transaction) or the past summary ?

By timestamp I meant the timestamp of the summary time.
