### ISSUE TITLE
AEWeb: provide an API to returns hash of all files content for a website

### ISSUE THREAD

**Issue by Neylix** [archethic-foundation/archethic-node#643]
### Is your feature request related to a problem?

In order to reduce request size for updating a website, we can return only the hash of the website files.
This issue is linked with https://github.com/archethic-foundation/aeweb-cli/issues/83

### Describe the solution you'd like

We can create a new endpoint under `web_hosting/get_files_hash/:address` which will retrieve the reference chain content, download all files of this website, hash their content and return a response like 
```
{
  "index.html" : "hash of index.html",
  "assets": {
      "favicon.png": "hash of favicon.png"
  }
}
```

**Comment by samuelmanzanera** [comment]
Good to have indeed. 

what do you think of `checksums` or `digest` instead of `get_files_hash` which is more the  desired intention ?

**Comment by internet-zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/643?planning-poker) with Zenhub @Neylix @samuelmanzanera @apoorv-2204

**Comment by samuelmanzanera** [comment]
> Hello.In aeweb we currently have: `base chain` , `ref chain` and `file chain`. how this two situations being handled? ->
> 
> 1. What if ref tx content size is too big, we create another ref tx?
> 2. if a user deploys an another website,  seed will be same, same ref chain. but different ref txn.
> 
> > which will retrieve the reference chain content, download all files of this website, hash their content and return a response like
> 
> What exactly is required here?
> 
> * Checksum api for a particular ref txn or complete ref chain, in a situation where use deploys multiple website.
>   since multiple website can have same file name but different hash.
>   do we want to return hash of file for particular ref tx?
>   or do we want to return digest of files for ref_chain?
>   like this `ref_txn_address => file_name => hash`?

1. For a ref tx to be too big, it must be 3MB of addresses referenced, which means (3MB * nb of addresses references)
For example with: 100 000 addresses ~0.34MB, means ~300GB for the website. So this aspect is not to consider I think.

 2. If the user wants to deploy another website, it must use another seed.
 
 
For the expectation, the digest should be based on the files listed in the reference tx. Hence the CLI will be able to determine which file must be uploaded and which file's addresss in the reference tx should be updated.

**Comment by apoorv-2204** [comment]
> ### Is your feature request related to a problem?
> In order to reduce request size for updating a website, we can return only the hash of the website files. This issue is linked with [archethic-foundation/aeweb-cli#83](https://github.com/archethic-foundation/aeweb-cli/issues/83)
> 
> ### Describe the solution you'd like
> We can create a new endpoint under `web_hosting/get_files_hash/:address` which will retrieve the reference chain content, download all files of this website, hash their content and return a response like
> 
> ```
> {
>   "index.html" : "hash of index.html",
>   "assets": {
>       "favicon.png": "hash of favicon.png"
>   }
> }
> ```
> 
> ### Additional context
> _No response_

1) for an api from node, we can hash the file itself during txn creation itself.
  example:
```  
"ARCHEthic_UCOnomics.pdf": {
     hash: "file_hash", 
    "encodage": "gzip",
    "address": [
    "0000565da0bcfd309a432d0764392b67d2a4e1d773d36c46586f4948ea291ad8c7a6"
    ]
```
```
"ARCHEthic_WhitePaper.pdf": {
    "encodage": "gzip", 
     hash: "partwise or complete hash" , 
    "address": [
      "00004e4a8561c74f02be2e13995a96bcc4071dbcfee3480beb5e264b1326e0be5c5f",
      "00003bdda8b4a56f588dafe0d14b6ee59592cec7cfbc4e106e1a45b536b05b6b07b6",
      "00009c92dce5faf3c6d27b5ff9330be0e8399d55063199caaaa17905cb87e65e1dbb"
    ]
  }
```
- disadvantages from fetching thorough api: 
   - unnecessary work load on cpu
   - network congestion.(multiple txn , some files spread over different tx, more pronounced in large websites)
   - blocking api call. leading to time out.
   
- Advantages of putting hash itself inside ref txn: 
    - no unnncessary load at node
    - no need of api
    - everything dependent on aeweb deploy-er.

2) nested structure 
``` 
"partners": {
      "build": {
        "bundle.css": {
          "encodage": "gzip",
          "address": [
            "0000565da0bcfd309a432d0764392b67d2a4e1d773d36c46586f4948ea291ad8c7a6"
          ]
        }
```
what you think about this?

```
partners/build/bundle.css: 
          hash: file_hash 
          "encodage": "gzip",
          "address": [
            "0000565da0bcfd309a432d0764392b67d2a4e1d773d36c46586f4948ea291ad8c7a6"
          ]
```
as with this naming, we can avoid a situation where can have same named files.


OR 

may different all together
```
 {
"file_hash" : 
{
  "file": "partners/build/bundle.css",
   "size": "456kb",
   "address": "address_list",
   encodage: "  gzip" 
   }
}
```
a hash based addressing

what do you think about this?

**Comment by apoorv-2204** [comment]
What do you think about something like this? 
we can use file path and hash / merle tree for source code changes, locally on aeweb cli, which read from last ref txn.
![Screenshot_20221124_172455](https://user-images.githubusercontent.com/90304197/203778527-a0bd0248-b8ec-4a4d-8b4f-15ec1a939394.png)

**Comment by bchamagne** [comment]
1/ I like to have the hash on the map. 
2/ I don't mind this syntax "/dir1/file1" to spare some bytes (looks like it's what was decided at first, see https://archethic-foundation.github.io/archethic-docs/participate/aeweb/how-it-works)
3/ I prefer "option 2" above because we will not have to fetch previous ref txns.
4/ While you're doing the hash, is it possible to have the file size at the same time? That'd be nice for the directory listing.
5/ A current limitation of AEWeb is the size of the ref txn. We can only upload a structure whose json is < 3MB. What you draw in "option 1" could be a solution to that issue.

**Comment by samuelmanzanera** [comment]
The hash in the map could be used to retrieve network calls and allow faster verification of the website integrity.

For the updated data, using the transaction chain by re-uploading the references like.

About the reference tx size limitation, the capacity to reach 3MB is so huge in terms of files(~30 000 with hashes and json structure)

**Comment by samuelmanzanera** [comment]
So, the effort should be on the CLI instead of the node, as the node will just return the content of the transaction. 
We can use the GraphQL API to fetch the ref tx

**Comment by apoorv-2204** [comment]
https://github.com/archethic-foundation/aeweb-cli/issues/86

**Comment by samuelmanzanera** [comment]
Epic: #1062
