### ISSUE TITLE
AEWeb: improve files response by caching their content

### ISSUE THREAD

**Issue by Neylix** [archethic-foundation/archethic-node#644]
### Is your feature request related to a problem?

Actually, each time a file is requested for a website, the API download the last reference chain, find the transaction address of the file content, download this transaction and return the file content.
If the browser request 50 files which are stored in the same transaction, the API will download 50 times the same transaction. This is not performant.

### Describe the solution you'd like

To fix this issue we can create a cache for AEWeb, which will store the most request transaction content.
The cache can have a configurable size, i.e. for a node with 16 Gb of ram, AEWeb cache could be 2 Gb.
This cache should store the transaction address, it's content and the last date this transaction has been requested.
If we reach the maximum size and want to add new content, the oldest requested file should be delete to be replaced by the new one.
The behavior of web_hosting will be the following: 
- A request is made for a genesis address and a file
- Request the last transaction address of the genesis address chain
- Check if this last transaction is in the cache
  - If not, download the transaction and store address, content and current time in the cache
  - If yes, get it's content from it and update last requested time with current time
- Find the address of the requested file
- Check if the transaction address is in the cache
  - If not, download the transaction and store address, content and current time in the cache
  - If yes, get it's content from it and update last requested time with current time
- Return the file content

**Comment by samuelmanzanera** [comment]
It can be a good idea.
But we have to identify hot websites for a welcome node. 
So the most requested websites would be cache (like in database engines with hot partitions). 

Also we could leverage disk for the hot websites but keep in ram association of websites files -> addresses, so less data to store on ram.

**Comment by Neylix** [comment]
> But we have to identify hot websites for a welcome node

This is why we store the last requested date for a file, so we always keep the most requested files in cache.

> Also we could leverage disk for the hot websites but keep in ram association of websites files

Yes good idea, we could store only the reference content in the memory as these transaction are read every time, and store the chain file on disk

**Comment by samuelmanzanera** [comment]
We should leverage Least Recently Used (LRU) cache strategy to determine the eviction order and hot websites

**Comment by internet-zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/644?planning-poker) with Zenhub @Neylix @samuelmanzanera @apoorv-2204

**Comment by bchamagne** [comment]
After a discussion with Sam yesterday, here's what I suggest:

We want to have 2 different caches, both will use the [Least Recent Used algorithm](https://en.wikipedia.org/wiki/Cache_replacement_policies#LRU). 
- The first one, called `CacheTransactionRef` is used to cache the reference transactions in memory. (save I/O requesting the reference transactions)
- The second one, called `CacheFile` is used to cache the files on disk. (save I/O requesting the data transactions)
We may have a small interation between both when a reference transaction is evicted from the `CacheTransactionRef` we can clear all related files in `CacheFile`

```
CacheTransactionRef
	- https://gitlab.com/barrel-db/erlang-lru package
	- key = website_address 
	- value = website's reference transaction json decoded
	- size: XXX MB - the package already deal with it
	- on evict: optimisation: also clear related files from the CacheFile (key= (website_address, _ ))
```

```
CacheFile
	- wraps https://gitlab.com/barrel-db/erlang-lru in a genserver to do the disk I/O and size limitation
	- key = (website_address, file_path)
	- value = path/of/cached/file/on/disk
	- size: XXX MB (here we cannot use the package's size feature, because it doesn't know the size of the files)
	- on write: also write to disk 
	- on evict: delete from disk 
	- on restart: wipe the entire directory (impossible to recreate it's state from the files alone)
```

**Comment by samuelmanzanera** [comment]
Epic: #1062
