### ISSUE TITLE
Fix self-repair notifier

### ISSUE THREAD

**Issue by samuelmanzanera** [archethic-foundation/archethic-node#645]
### Describe the problem you discovered

The current implementation of the self-repair notifier is not correct.
Some changes are required.

### Describe the solution you'd like

To correct if we should:
- [x] 1)  Exclude network transactions (as they are synchronized on all the nodes – no need of notifier for those)
- [x] 2) Read the transaction before to send it (for now, we are not sending the entire transaction, only the summary)
- [x] 3) Check if the transaction exists before to send it (to avoid sending significant amount of data)
- [x] 4) Add a flag in the transaction validator to not validate transaction movements in the `ReplicateTransaction` message
- [x] 5) Using a stream by chain to have the transactions in order

**Comment by internet-zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/645?planning-poker) with Zenhub @samuelmanzanera @Neylix @apoorv-2204

**Comment by samuelmanzanera** [comment]
Closed by #671
