### ISSUE TITLE
LastTransaction with public key

### ISSUE THREAD

**Issue by redDwarf03** [archethic-foundation/archethic-node#670]
### Is your feature request related to a problem?

In the wallet, contacts can be created to help users send transactions or to declare public keys that can access secrets.
So, at a given time, we attach an address and a public key to this contact.

When the user enters an address, we check if it is a contact by comparing the last transaction of the address entered and that of the contact. If it is the same transaction, it means that the address is that of the contact.

I would like to do the same for the public key. But it would be necessary to have as search criteria in the graphql query "lastTransaction", the value of previousPublicKey

Is this possible?

Thx

**Comment by Neylix** [comment]
This can be done by hashing the public key to retrieve the address, then use the `last_transaction` api of graphql and getting the previous public key of the transaction returned
