### ISSUE TITLE
Check transaction's address existence during validation

### ISSUE THREAD

**Issue by samuelmanzanera** [archethic-foundation/archethic-node#678]
### Is your feature request related to a problem?

For now, the transaction's address existence is checked on the replication nodes
It might occur – due to network failure, sync failure or split brain – two transaction with the same address are replicated by the network, causing chain inconsistency and therefore invalid proof of integrity for the chain by the next transaction.

### Describe the solution you'd like

So to increase consistency in the transaction validation across multiple cross validation nodes, the existence should also be checked in the validation stamp.
We can add in the pending transaction validation a check to ensure the transaction is not already replicated and store this error result in the validation stamp.

**Comment by internet-zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/678?planning-poker) with Zenhub @samuelmanzanera @apoorv-2204 @Neylix
