### ISSUE TITLE
Upnp port forwarding fail on local ip change

### ISSUE THREAD

**Issue by Neylix** [archethic-foundation/archethic-node#698]
### Describe the problem you discovered

Actually we use miniupnpc for port forwarding, it tells to the router to redirect incoming request on a specific port to the node local ip.
But if the local ip of the node changes, the new upnp request will fail because the router already has a redirection on this port

### Describe the solution you'd like

Before using upnp to forward the port, we should check if there is already a redirection on this port.
If there is no redirection -> continue and forward port
If there is a redirection on the same local ip -> continue and forward port (to update time limit)
If there is a redirection on a different local ip -> remove the existing redirection then continue and forward port

**Comment by roychowdhuryrohit-dev** [comment]
Why not use mac binding to disable local IP change?
