### ISSUE TITLE
Forwarding random port with upnpc

### ISSUE THREAD

**Issue by Neylix** [archethic-foundation/archethic-node#700]
### Describe the problem you discovered

In previous implementation, while forwarding to port 0, the router was redirecting a random port. But since we use miniupnpc, we cannot anymore forward the port 0, so we cannot open a random port automatically.

### Describe the solution you'd like

We have 2 options : 
- Consider using an other tool for port forwarding like https://github.com/benoitc/erlang-nat if this implementation is working well it would be better than having a upnpc programm compiled in C and opening a random port using 0 works in this lib
- Determining a list of port possibility and taking a random number until the port opening is working

**Comment by apoorv-2204** [comment]
> ## Update 

'https://github.com/benoitc/erlang-nat'
With the upnp capability enabled or disabled, my local network is inoperable with this nat lib operations, and I am unable to connect to other nodes.
### Proposed solution:
1) Continue with option nb 2,
2) Build a cli to ask you for input for env variables. else they can move with default

![image](https://user-images.githubusercontent.com/90304197/210516649-a4c46078-b855-4b1a-9848-4812f987aee9.png)
