### ISSUE TITLE
For explorer, fetch data from DB if they are available

### ISSUE THREAD

**Issue by Neylix** [archethic-foundation/archethic-node#730]
### Is your feature request related to a problem?

Explorer will be consulted by a lot of people, and so the node will request a lot of informations on the network.
To reduce the network charge and enhance the explorer speed, we should first check if the information needed is accessible from the node DB before requesting it on the network.

### Describe the solution you'd like

Actually the explorer uses 2 modules to fetch informations `Archethic` and `BeaconChain`.
We could remove the direct request on `BeaconChain` and only ask informations on `Archethic` module.

As it, in the `Archethic` module, we can try to fetch the information from DB and return it if it exists, if not then we request the network using quorum.

**Comment by apoorv-2204** [comment]
we did impl it?
