### ISSUE TITLE
Add `get_first_address` in smart contract library

### ISSUE THREAD

**Issue by samuelmanzanera** [archethic-foundation/archethic-node#740]
Provide a function to retrieve the first address from any address within the smart contract interpreter.

**Comment by internet-zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/740?planning-poker) with Zenhub @apoorv-2204 @netboz @Neylix @samuelmanzanera @tenmoves

**Comment by samuelmanzanera** [comment]
Closed by #819
