### ISSUE TITLE
Add resolved destination in smart contract constants

### ISSUE THREAD

**Issue by samuelmanzanera** [archethic-foundation/archethic-node#741]
For now, the UCO or token transfers used in the smart contract are the one passed in the transaction but not the one resolved (ie. last addresses)
This might can create an issue if the code requires some exchange towards the contract, as the callers might not know the last address of the contract.

So, we may add another field in the constants for the list of resolved UCO or token transfers.

**Comment by internet-zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/741?planning-poker) with Zenhub @apoorv-2204 @netboz @Neylix @samuelmanzanera @tenmoves
