### ISSUE TITLE
Write inputs of burn address in DB instead of keeping it in memory

### ISSUE THREAD

**Issue by Neylix** [archethic-foundation/archethic-node#796]
### Is your feature request related to a problem?

The burn address is designed to receive a lot inputs due to burning movement. But this address will never do a transaction and so the inputs will be accumulated forever.
All the inputs of an address are stored in memory (ets table) until there is a new transaction in this chain. For the burn address we would like to have a different behavior.

### Describe the solution you'd like

While adding an inputs to an address, we should check if this address is the burn address, if so, we should write the inputs directly in DB and not keep them in memory

### Additional context

We should also create a migration function to create the DB file, write all existing inputs inside and clear the ets table

We can also have some reflexion about other addresses thay may have a lot of inputs. These inputs should not take too much memory space. Maybe a behavior like when an address has more than x inputs, they are all written into disk. So there would not be a different behavior for the burn address

**Comment by samuelmanzanera** [comment]
This is true for the intentional burn. What about the transaction's fee ? Do we want to save them on disk during transaction validation or only during self-repair ?

**Comment by internet-zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/796?planning-poker) with Zenhub @apoorv-2204 @netboz @Neylix @samuelmanzanera @tenmoves
