### ISSUE TITLE
Refactor Message module

### ISSUE THREAD

**Issue by Neylix** [archethic-foundation/archethic-node#799]
### Is your feature request related to a problem?

Actually all serialization and deserialization are done in the message module, but as the number of message growth, the reaadability of this module and it's testing begin to be complex.

### Describe the solution you'd like

We should refactor this module to improve test and readability.
The serialization and deserialization could be done in the module of the message itself, an actual example is the `ShardRepair` message which use
```elixir
def encode(msg = %ShardRepair{}) do
  <<230::8, ShardRepair.serialize(msg)::bitstring>>
end
```
The testing part of serialization and deserialization can be done in doctest of this message

We can also put in the message itself the process, for example: 
```elixir
def process(msg = %ShardRepair{}) do
  ShardRepair.process(msg)
end
```
To go further we don't need to patern match de message type, but directly call the structure, so there would be only 1 function process in the Message module:
```elixir
def process(msg) do
  msg.__struct__.process(msg)
end
```

To encode and decode a message we need to know the id number of it. We could create a correspondence table like 
```elixir
id_map = %{
  ShardRepair => <<230>>,
  ... => ...
}
```
So we could have 1 function for encoding and decoding :
```elixir
def encode(msg) do
  msg_id = Map.get(id_map, msg.__struct__)
  serialized = msg.__struct__.serialize(msg)
  <<msg_id::8, serialized::binary>>
end

def decode(<<msg_id::8, rest::binary>>) do
  {msg_type, _} = Enum.find(id_map, fn {key, value} -> value == msg_id end)
  msg_type.deserialize(rest)
end
```

**Comment by apoorv-2204** [comment]
can we have Message.Request.ShardREapir
Message.Response.OK

??

**Comment by samuelmanzanera** [comment]
Instead of 
```elixir
msg_id = Map.get(id_map, msg.__struct__)
serialized = msg.__struct__.serialize(msg)
<<msg_id::8, serialized::binary>>
```

We should do something like:

```elixir
msg_id = Map.get(id_map, msg)
serialized = msg.serialize(msg)
<<msg_id::8, serialized::binary>>
```

or even implement a protocol:
```elixir
Message.serialize(msg)
```

**Comment by tenmoves** [comment]
I think leveraging polymorphism with protocols is the best way to go for me.

**Comment by internet-zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/799?planning-poker) with Zenhub @samuelmanzanera @Neylix @netboz @apoorv-2204

**Comment by internet-zero** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/799?planning-poker) with Zenhub @tenmoves
