### ISSUE TITLE
AEWeb: display the size when listing the files of a directory

### ISSUE THREAD

**Issue by bchamagne** [archethic-foundation/archethic-node#800]
### Describe the solution you'd like

We added the size (in bytes) of every files in the reference transaction. 
We can now add a column to display the size of every files when listing the files of a directory: 

![image](https://user-images.githubusercontent.com/74045243/210397946-5cf43eba-8770-4a38-b0b6-e5fef049e286.png)

### Additional context

Example of a reference transaction:

```
{
  "aewebVersion": 1,
  "hashFunction": "sha1",
  "metaData": {
    "dir1/file10.txt": {
      "hash": "d5772baf70d86e28b3349580569f58b3ec1a8db9",
      "size": 8,
      "encoding": "gzip",
      "addresses": [
        "0000942ea8e9246f51f589373075bf09e3490c34138ce63702b3a27336bac8316168"
      ]
    },
    ...
}
```

**Comment by tarunsamanta2k20** [comment]
I would like to contribute to this issue. Please assign it to me.

**Comment by tarunsamanta2k20** [comment]
@Neylix How to run this project?

docker login require

**Comment by tarunsamanta2k20** [comment]
RROR: pull access denied for archethic-node, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by Neylix** [comment]
> @Neylix How to run this project?
> 
> docker login require

Hello, I recommend you to not use docker for developing as every change you do you will need to rebuild docker image which takes several minutes.
Instead you can install erlang and elixir (if you are on linux, you can run the script in `scripts/install.sh`) then use iex -S mix to run the project

**Comment by Neylix** [comment]
> @Neylix sed: can't read /etc/needrestart/needrestart.conf: No such file or directory ******* FAILED *******

You can remove the line 14 of install.sh file 
```bash
sudo systemctl mask sleep.target suspend.target hibernate.target hybrid-sleep.target
```

**Comment by tarunsamanta2k20** [comment]
src/c/crypto/tpm/lib.c:5:10: fatal error: tss2/tss2_esys.h: No such file or directory
    5 | #include <tss2/tss2_esys.h>
      |          ^~~~~~~~~~~~~~~~~~

**Comment by Neylix** [comment]
> src/c/crypto/tpm/lib.c:5:10: fatal error: tss2/tss2_esys.h: No such file or directory 5 | #include <tss2/tss2_esys.h> | ^~~~~~~~~~~~~~~~~~

If you run this manually, do you have any error ? 
```bash
wget https://github.com/tpm2-software/tpm2-tss/releases/download/3.2.1-rc2/tpm2-tss-3.2.1-rc2.tar.gz
tar -xf tpm2-tss-3.2.1-rc2.tar.gz --one-top-level=tpm2-tss --strip-components 1
rm tpm2-tss-3.2.1-rc2.tar.gz && cd tpm2-tss
./configure --with-udevrulesdir=/etc/udev/rules.d
make -j$(nproc)

sudo make install
sudo sed -i "s/tss/$(whoami)/gi" /etc/udev/rules.d/tpm-udev.rules
sudo udevadm control --reload-rules && sudo udevadm trigger
sudo ldconfig
sudo apt install tpm2-tools -y
```

**Comment by tarunsamanta2k20** [comment]
@Neylix ,

I am pushing it, please run it

**Comment by tarunsamanta2k20** [comment]
I am getting many config errors

**Comment by tarunsamanta2k20** [comment]
Somehow run it

Please tell me the endpoint for getting this indexof screen

**Comment by Neylix** [comment]
> Somehow run it
> 
> Please tell me the endpoint for getting this indexof screen

You can look at AEWeb documentation here : https://archethic-foundation.github.io/archethic-docs/participate/aeweb/

You need to use aeweb_cli to deploy website : https://github.com/archethic-foundation/aeweb-cli

Code relative to AEWeb is in `lib/archethic_web/controllers/api/web_hosting_controller.ex`

**Comment by tarunsamanta2k20** [comment]
Endpoint for this screen in localhost

![210397946-5cf43eba-8770-4a38-b0b6-e5fef049e286](https://user-images.githubusercontent.com/55488549/210615803-23cd6928-417e-46b6-ad8d-99ca38f3d131.png)

**Comment by bchamagne** [comment]
Hello, thanks for taking this issue ! 

# First step: 
Start a node as described in README.md 

# Second step
The first thing you need to do is to upload a folder to AEWeb (https://github.com/archethic-foundation/aeweb-cli):

```
[bastien@T495 aeweb-cli]$ ./aeweb.js deploy --endpoint http://127.0.0.1:4000 --seed bastien --path /tmp/mydir/
Connecting to http://127.0.0.1:4000
Creating file structure and compress content...
Creating transactions ...
Estimating fees ...
Total Fee Requirement would be : 13.48326625 UCO ( $ 1.24 | € 1.16), for 27 transactions.
Do you want to continue. (yes/no) yes
Sending 27 transactions...
Transaction 1...
Waiting transaction validation...
Transaction confirmed !
See transaction in explorer: http://127.0.0.1:4000/explorer/transaction/0000f9b8d3eeb102cf2a11cd0b566aa9c9c651cf11814b30de1d5466c51decbc1952
-----------
[...]
-----------
Transaction 27...
Waiting transaction validation...
Transaction confirmed !
See transaction in explorer: http://127.0.0.1:4000/explorer/transaction/0000b5c0890d3bc52003f9279db6c22cf602bef7c08319ff765aea31c2c1ac919830
-----------
Website is deployed at: http://127.0.0.1:4000/api/web_hosting/00007d9167bdce9dbb1258501c3bc3a48494773554e5ceab15896d1617f5a6285683/
```

The URL of this upload is displayed last: http://127.0.0.1:4000/api/web_hosting/00007d9167bdce9dbb1258501c3bc3a48494773554e5ceab15896d1617f5a6285683/

----
In the code, this page is generated in `ArchethicWeb.API.WebHostingController.DirectoryListing` module.
I'll update the documentation with a meaningful example asap.
Hope this help!

**Comment by samuelmanzanera** [comment]
Epic: #1062
