### ISSUE TITLE
previous don't work on last page

### ISSUE THREAD

**Issue by tenmoves** [archethic-foundation/archethic-node#818]
### Describe the problem you discovered

When you are on the explorer and you have multiple pages, next and previous button work normally until you reach the last page.
On the last page previous button doesn't work anymore, this problem is present on all the views with multiple pages.

![image](https://user-images.githubusercontent.com/11648790/211565257-8f13d7e0-649b-4688-b039-42290c2bd85e.png)

### Describe the solution you'd like

When you are on the last page, previous page button should switch the view to the previous page like the behaviour it has on the other pages.

**Comment by ArceusDev** [comment]
Hey there! so I am a complete noob. can you tell me what knowledge I need to solve this issue?

**Comment by tenmoves** [comment]
hello @ArceusDev, thank  you for your interest, for this issue you need a little knowledge of Elixir / Elixir liveview (https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html). 
Normally it should be a small issue.

**Comment by tenmoves** [comment]
update: the bug appears when we arrive at the last page and we still click on next this message is displayed on the websocket coonsole : 
`socket: disconnect for page nav -  undefined
utils.js:28 phx-FzusWNUngMjTHRDH destroyed: the child has been removed from the parent -  undefined
utils.js:28  destroyed: the child has been removed from the parent`

however if we don't click previous still work normally
