### ISSUE TITLE
Enhance Oracle services data fetching with self hydrating cache

### ISSUE THREAD

**Issue by netboz** [archethic-foundation/archethic-node#824]
### Is your feature request related to a problem?

- We might need a per-service refresh frequency
- Currently if a service is not responding the service time-out is added to oracle transaction processing time.
- Later, as more services will be added ( meteo, ... ), we will need a solution that can scale better
- This will bring also a TTL to the services values

### Describe the solution you'd like

This can be achieved by integrating a ["self hydrating"](https://gitlab.com/yan.guiborat1/cache) cache between the services and the scheduler.

The cache will be started at node startup.
The cache, at initialisation will retrieve the services list and the hydrating ( update ) function from node configuration.
If the scheduler request a value for which the hydrating function is running, then the cache will wait for function execution termination before returning the value.

**Comment by internet-zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Workspace-61efec9c93391c001e69a6dc/issues/archethic-foundation/archethic-node/824?planning-poker) with Zenhub @samuelmanzanera @Neylix @netboz
