### ISSUE TITLE
SC functions to work on lists

### ISSUE THREAD

**Issue by bchamagne** [archethic-foundation/archethic-node#826]
### Is your feature request related to a problem?

When writing SC, we need functions to be able to work on lists. 

### Describe the solution you'd like
We could add a map/filter/reduce. What would be the syntax?

**Comment by bchamagne** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Workspace-61efec9c93391c001e69a6dc/issues/archethic-foundation/archethic-node/826?planning-poker) with Zenhub @apoorv-2204 @Neylix @samuelmanzanera @tenmoves @netboz @bchamagne

**Comment by samuelmanzanera** [comment]
I think we can create a new `reduce` function, which will serve all the purposes

**Comment by bchamagne** [comment]
> I think we can create a new `reduce` function, which will serve all the purposes

What about the syntax, shoud we include elixir's lambdas in the SC?

`reduce(list, 0, fn item, acc -> acc end)`

**Comment by samuelmanzanera** [comment]
> > I think we can create a new `reduce` function, which will serve all the purposes
> 
> What about the syntax, shoud we include elixir's lambdas in the SC?
> 
> `reduce(list, 0, fn item, acc -> acc end)`

if we don't want to allow lamba functions and to simplify the language, we could leverage macro's style

```elixir
agg = reduce inputs do
   ...
end
```

**Comment by netboz** [comment]
I browsing some docs a few days ago, looking for equivalent of erlang's filtermap in Elixir, and I remember I read that all Enum api can be reproduced using two of the Enum module provided fonctions. Something like all logic operations can be made from NAND doors.
I will try to find back what are these two fonctions which could be good candidates for a port to smart contracts.

**Comment by samuelmanzanera** [comment]
Another proposition to help the readability as sentence

```elixir
reduce get_calls(), as: input, with: [my_var_in_acc: 0] do
  
end
```
