### ISSUE TITLE
Reward month occurence is static

### ISSUE THREAD

**Issue by Neylix** [archethic-foundation/archethic-node#827]
### Describe the problem you discovered

To calculate the reward for a node reward transaction, we need to know how many node reward transaction there will be in a month. To calculate this number, we have a function that provide the number of occurence for a month based on the reward scheduler interval.
The problem is that this number is calculated on compile time, but it should evolve depending of the current month.
It may cause error in reward amount, and if 2 nodes didn't compile the code on the same month, they will have different value for the reward amount causing node reward transaction to fail.

### Describe the solution you'd like

Each month, the number should be updated with the current month

**Comment by tenmoves** [comment]
we can do a cronjob to update this value every month, it's always a bad idea to have long running processes (or genservers).

**Comment by samuelmanzanera** [comment]
The idea would be to use a conf in module attributes to determine the number of days by month and taking in charge the leap years
