### ISSUE TITLE
[BUG] [AEWEB] Cant explore files

### ISSUE THREAD

**Issue by apoorv-2204** [archethic-foundation/archethic-node#833]
### Aeweb faces two issues

- [ ] When website updates has no index.html, we should be able to explore the directory, instead clicking on any file, doesn't browse it. look below
  -![image](https://user-images.githubusercontent.com/90304197/212637224-44cf4135-d47b-48a3-b5c3-280771e9398e.png)
 `<a href="//api/web_hosting/0000028cc0478586910bb2f2ab765361254246f430c327c8105dd995addfc15866b9/aelogo.png"><i clasSs="file icon"></i> aelogo.png</a>`

![image](https://user-images.githubusercontent.com/90304197/212637237-61655aeb-9f2b-4d83-9b64-d49f9ebf86bb.png)

![image](https://user-images.githubusercontent.com/90304197/212637253-10d3c5e3-afb6-4a62-9534-c1c27f8bed17.png)

**Comment by samuelmanzanera** [comment]
Epic: #1062
