### ISSUE TITLE
Stop replication at previous transaction while streaming previous chain

### ISSUE THREAD

**Issue by Neylix** [archethic-foundation/archethic-node#835]
### Describe the problem you discovered

Since the `get_transaction_chain` in DB do not stop at the transaction received in parameter, there is a problem in the self repair.
When replicating a transaction, the function `stream_previous_chain` will return the entire chain, so the next transactions of this chain in the summary will already be replicated and the self repair will crash because of a transaction already exists

### Describe the solution you'd like

The function `stream_previous_chain` and `stream_previous_network_chain` in replication/tansaction_context should stop at the `previous_address` requested with a `Stream.take_while` for exemple

**Comment by samuelmanzanera** [comment]
This was indeed the purpose of the limit address

**Comment by samuelmanzanera** [comment]
Indeed we can limit the stream to tackle this issue.

**Comment by samuelmanzanera** [comment]
Indeed we can limit the stream to tackle this issue.
