### ISSUE TITLE
Contract Loader: should be able to load a contract & trigger recipients at the same time

### ISSUE THREAD

**Issue by bchamagne** [archethic-foundation/archethic-node#866]
### Describe the problem you discovered

When loading a transaction from the network (from_db = false), the `Archethic.Contracts.Loader.load_transaction/2` will not both load a contract & trigger the recipients. It will load the contract but not trigger the recipients.

We need to do both (to handle the "contract A triggers contract B" case).

**Comment by internet-zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/866?planning-poker) with Zenhub @apoorv-2204 @bchamagne @netboz @Neylix @samuelmanzanera @tenmoves
