### ISSUE TITLE
SC: be able to verify that transfers are done only to "callers"

### ISSUE THREAD

**Issue by bchamagne** [archethic-foundation/archethic-node#867]
### Is your feature request related to a problem?

In `condition inherit`, we'd like a function to be able to ensure that all transfers are done to "callers" of the contract.
I call "callers" the addresses that sent a transaction with the contract as a recipient.

### Describe the solution you'd like

proposition:
```
condition inherit: [
  uco_transfers: only_calls
]
```

### Additional context

For example, for a faucet-type contract, we could ensure that there is no transfer to anyone else than "callers".

**Comment by samuelmanzanera** [comment]
I think we have to think broader. 
You have to check the callers but also the right amount. 
So maybe something like `Enum.any` would help allowing more custom code to be mentioned.

**Comment by bchamagne** [comment]
I'm closing this one, as @samuelmanzanera mentioned, there is a broader feature emerging. 
We might want to be able to write code in the conditions, similar to actions.

```
condition inherit: [
  uco_transfers: (
  found = false

  for x: next.uco_transfers do 
    if x.to == "010101" do 
      found = true 
    end
  end

  found
  )
]
```

I'll create a new issue.
