### ISSUE TITLE
Try to re run self repair if it fails

### ISSUE THREAD

**Issue by Neylix** [archethic-foundation/archethic-node#871]
### Describe the problem you discovered

For some reason the self repair may fail. For example if during the self repair a node has a connection problem, it will not fetch the beacon summaries and so it will crash the self repair. But when the node is connected again, it continue to validate transaction but it's p2p view may be invalid or have missed some transaction (node shared secret for example). This causing election error.

### Describe the solution you'd like

To avoid this problem, if the self repair ends with an error, we should immediately try to rerun it until it run succesfully. This should happen for bootstrap sync and self repair scheduler I think

If the self repair crahes, the node should not continue to do things. For this we need to stop all scheduler and stop the HTTP / P2P listener.
To implement this behavior we can manage with the PubSub with up and down event

**Comment by internet-zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/871?planning-poker) with Zenhub @apoorv-2204 @bchamagne @netboz @Neylix @samuelmanzanera @tenmoves
