### ISSUE TITLE
Welcome node should forward tx if not synced

### ISSUE THREAD

**Issue by Neylix** [archethic-foundation/archethic-node#872]
### Describe the problem you discovered

When a welcome node receive a transaction, it will perform the election for validation nodes and send to them the StartMining message.
But if the welcome node is out of sync and don't have the last node shared secret, it's election will be wrong (election or proof of election).

### Describe the solution you'd like

To fix this, when receiving a transaction, the welcome node should verify that it has the last node shared secret transaction.
If yes, continue as actually, if not we have 3 options:
- Forward the transaction to another authorized node
- Request the last node shared secret transaction and replicate it, then continue to send the transaction (if multiple transaction are received, the node may try to replicate multiple time the shared secret)
- Forward the transaction to another authorized node, and try to replicate the last node shared secret (if multiple transaction are received, the node may try to replicate multiple time the shared secret)

We should take care to continue to have the right welcome node which is the first one the client sent his transaction

**Comment by internet-zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/872?planning-poker) with Zenhub @Neylix @samuelmanzanera @apoorv-2204 @bchamagne @netboz @tenmoves
