### ISSUE TITLE
Ensure each code proposal includes appup

### ISSUE THREAD

**Issue by samuelmanzanera** [archethic-foundation/archethic-node#873]
In the current version, code proposals are built from text/plain style:
```
Description: ......
Changes:
{git diff}
```

However, to be complete and to avoid unexpected results during the upgrade, we should require the appup instructions to be present.
Hence, we could check the impact of the code proposals and the proposal's correctness.

**Comment by internet-zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/873?planning-poker) with Zenhub @apoorv-2204 @bchamagne @netboz @Neylix @samuelmanzanera @tenmoves
