### ISSUE TITLE
AEWeb: if url is a folder and there is an index.html inside, serve the index.html 

### ISSUE THREAD

**Issue by bchamagne** [archethic-foundation/archethic-node#874]
### Describe the problem you discovered

If there is a index.html file in a folder, and user tries to access folder directly, we'd like to serve the index.html file.
This way users can upload multiple websites in a deployment.

### Describe the solution you'd like

We have this behaviour on the root folder already. We want the same behaviour for any folder.

**Comment by samuelmanzanera** [comment]
Epic: #1062
