### ISSUE TITLE
scripts/test-release.sh should support an argument

### ISSUE THREAD

**Issue by tenmoves** [archethic-foundation/archethic-node#891]
### Is your feature request related to a problem?

Right now we create 2 erlang vms to test the release, we want to extend this functionality and make the script accept an integer argument and create as many erlang vms as this argument.

### Describe the solution you'd like

refactor the script to accept a  integer as argument and create as many vms.
argument should be between 1 and 8.
scripts/test-release.sh --instances 5 should create 5 vm instances
scripts/test-release.sh  --instances 0 should return an error (value not between 1 and 8)

**Comment by Neylix** [comment]
Issue fixed by https://github.com/archethic-foundation/archethic-node/pull/1117
