### ISSUE TITLE
Transaction amount should verify it is BigInt

### ISSUE THREAD

**Issue by Neylix** [archethic-foundation/archethic-node#893]
### Describe the problem you discovered

Actually user can create smart contract like this :
```elixir
actions triggered_by: transaction do
  # quantite d’UCO reçu
  amount_send = transaction.uco_transfers[contract.address]
  if amount_send > 0.5 do
      # Conversion UCO en token test
      token_to_credit = amount_send * 10 - 0.5

      # Nouvelle transaction
      set_type transfer
      add_token_transfer to: transaction.address, token_address: "000052EE087848D039231528532B53B1182C40508B30B3FBB8AB5F616A46484F6241" , amount: token_to_credit
  end
end
```

The number 0.5 causes problem as all amount should be in BigInt, so in this case, the final amount will be a float causing this error : 

![image](https://user-images.githubusercontent.com/26260538/217191281-ba1d2c95-67eb-45aa-bbf1-e539c62d6344.png)

### Describe the solution you'd like

At some point (define where) we should ensure that the amount of a transfer is an integer

**Comment by bchamagne** [comment]
I think we should have a BigInt struct manipulated by a BigInt module. And the transfer function should only accept that struct and neither integer and float

**Comment by samuelmanzanera** [comment]
We can convert every number to big int transparently. The user/developer will write as usual in Base10 and will be converted to 1e^8

**Comment by Neylix** [comment]
We should be care of edge case like string interpolation where we should control if the variables or function call is an BigInt and convert it to decimal number

**Comment by bchamagne** [comment]
> We can convert every number to big int transparently. The user/developer will write as usual in integer/float and will be converted to 1e^8

Summary of today's discussion with both of you: 

There are 2 issues to tackle: 

1. float rounding issue when doing maths 
2. token/uco amount should be BigInt (1 UCO = 100_000_000)


The solution to 1 is to convert the numbers to bigint before doing the maths and convert back to numbers right after.
This way we have no rounding issue. (We'll still truncate to 8 decimals, no work around that)

The solution to 2 is to modify the `add_uco_transfer` and `add_token_transfer` to cast to bigint. And when reading `uco_transfers` and `token_transfers` from an existing transaction, decast the bigint. 

This way it is completely transparent for the user. No bigint and no rounding issues.

**But this will be a breaking change.** What used to be `amount: 200_000_000` is now `amount: 2`
