### ISSUE TITLE
Constantly re synchonize network transactions

### ISSUE THREAD

**Issue by Neylix** [archethic-foundation/archethic-node#912]
### Describe the problem you discovered

Actually if a node missed some network transaction it will never be agree with other nodes and consensus error is reached. This is normally fixed on the next self repair, but it may occur in multiple hours and this is blocking transaction for a long time.
We should have a resynchronization workflow without waiting for next self repair.

### Describe the solution you'd like

Here is a possible solution: 
When a welcome node receive a transaction, it get from it's DB all the last information about network transaction:
- last oracle transaction address
- last node shared secret transaction address
- last origin transaction address (for all origin type)
- all the last public key of authorized and available nodes

Then it concatenate all these informations, create a hash and add it to the StartMining message

When the validation nodes receive this message, they will get the same informations, hash them and compare it with the one received. Here multiple case can occurs: 
- For validation node:
    - The hash is the same, start transaction mining and return Ok to the welcome node
    - The hash is not the same, do not start mining, start a resync*, respond an error to the welcome node
 - For welcome node:
     - If all node return Ok, nothing more to do
     - If only one or zero node return Ok (only error) then forward the transaction to another authorized node and start a resync* (The transaction will not be validated as there is not enough validation node)
     - If a node responded with an error, but at least two nodes responded Ok, start a resync* (transaction will be validated with the 2 or more Ok nodes)

**We may have the same hash behavior when the validation node send the ValidateTransaction message to the replication nodes.**

\* Resync means verify and replication missing network transaction:
- For scheduled network transaction (oracle, node shared secret), we can compare the previous scheduled time and the timestamp of the last transaction of this chain, if timestamp >= last schedule time it means this chain is synchronize, otherwize we need to request the last transaction and replicate it
- For non scheduled network transaction (node, origin) we need to request the last transaction of these chain and replicate it (if not already stored)

The resync process should use the RepairWorker used by the Notifier workflow to not start replicating multiple time the same transaction if we receive a lot of transaction to mine.

This workflow permit to synchronize along the day the potentially missed transactions. It can be improved but degrading the low message size:
Instead of creating a hash of all the network state, we can pass the timestamp of the last transaction of these chains. So when a node have a difference, we can know which node missed a network transaction and so start the repair only on this node. But the StartMining / ValidateTransaction messages will have an increased data size and the behavior to determine in which case we start or not the mining is more complex to determine

**Comment by samuelmanzanera** [comment]
As discussed, the validation part could be implemented effortlessly and be really effective.

The advantage of the hash is to give to the protocol a proof or a network state snapshot.

Regarding the replication side, we could leverage the hash to make sure the network's state is consistent as well and start to validate the transaction regarding the new state.
