### ISSUE TITLE
Smart Contracts: Time.now() should be idempotent

### ISSUE THREAD

**Issue by bchamagne** [archethic-foundation/archethic-node#921]
### Describe the problem you discovered

`Time.now()` should not return the current timestamp. 
Because it will have different values on different nodes which means different results and impossible to compare them.

### Describe the solution you'd like

Return value should depends on the trigger type.

**transaction**: transaction.timestamp
**datetime**: datetime
**interval**: the timestamp truncated somehow?
**oracle**:

**Comment by samuelmanzanera** [comment]
We should also update the documentation to mention the time is not the real current time (seconds or millisecond) but the time of the trigger.
