### ISSUE TITLE
Smart Contracts: validation workflow

### ISSUE THREAD

**Issue by bchamagne** [archethic-foundation/archethic-node#925]
### Is your feature request related to a problem?

Currently, there are N storage nodes for the smart contract current transaction. When the contract is triggered, all of them execute the contract, but only the first one creates the "next transaction" (with a fallback mechanism if node is unavailable). 
Then the storages nodes of "next transaction" will check the inherit conditions.

### Describe the solution you'd like

We might want to check that all contracts executions resulted in the same "next transaction".

### Additional context

Epic: #306

**Comment by samuelmanzanera** [comment]
I think the "all contract executions" is the purpose of the atomic commitment consensus. So during transaction validation nodes are ensure the next one is the good one.

**Comment by Neylix** [comment]
I think @bchamagne is talking about the action block and not the inherit constraint.
Actually a single node execute and send the transaction, but all nodes trust this transaction to be the expected one created by the action block

**Comment by samuelmanzanera** [comment]
The purpose of the atomic commitment is also to check this kind of behavior, so we should add validation check if previous transaction has a contract's code. Hence the pending transaction should reflect the result of the action's code.
