### ISSUE TITLE
Smart Contracts: Contract.get_calls() should query the network

### ISSUE THREAD

**Issue by bchamagne** [archethic-foundation/archethic-node#926]
### Is your feature request related to a problem?

`Contract.get_calls/0` is currently a local DB call. 
This is wrong for 2 reasons: 

1. when dealing with inputs, you cannot trust yourself enough to have received all inputs, it's best to ask others.
1. the `condition inherit` block is not executed by the same node; this one does not have access to the inputs in local DB

### Describe the solution you'd like

We need `get_calls` to do a quorum.

**Comment by samuelmanzanera** [comment]
For the 2nd point, because during transaction validations we get the inputs of the transaction to be validated, we get the contract calls. So, we could override the `get_calls` function to leverage the inputs already fetched in the transaction validation. @bchamagne would be possible?

**Comment by samuelmanzanera** [comment]
> Currently the `get_calls` is a side-effect (read from DB). Instead, we could  pass the calls to the `execute_trigger` and `valid_conditions?` functions instead. That'd be elegant but we probably do it for nothing on many contracts that don't use it. 
> 

The inputs are already fetched in tx validation, so we will just leverage them in the interpreter functions
