### ISSUE TITLE
Storage node should ensure the distributed election

### ISSUE THREAD

**Issue by Neylix** [archethic-foundation/archethic-node#960]
### Describe the problem you discovered

After all the validation node agreed and reached the consensus without error, they ask the storage node to validate the transaction. These nodes verify if the election is valid, but they only verify that the signature are valid.
So a malicious node could sign both validation stamp and cross validation stamp, and the storage node will return a true value because the signature are valid while they should be from different node.

### Describe the solution you'd like

When a storage node ensure the election is valid, it should ensure that all the signing node are different.

PS: There is only one case where the coordinator node can be the same as the cross validation node, it's when there is only 1 validation node and it run into the standalone workflow.
So the different signature should be verified only if there is multiple node returned by the validation node election.

**Comment by samuelmanzanera** [comment]
Duplicated of #980
