### ISSUE TITLE
Smart Contracts: trigger `datetime` should be rounded to the minute.

### ISSUE THREAD

**Issue by bchamagne** [archethic-foundation/archethic-node#992]
### Describe the problem you discovered

With current datetime worflow, there is a possibility for a contract to run every second. 
We must handle this case by rounding the datetime to the closest minute.

### Additional context

Epic: #608

**Comment by samuelmanzanera** [comment]
We could probably check in the interpreter parser than the timestamp should not include second (only 0s) . Hence the timestamp would always be minute based.
